"""Tests for puremacro.korv_gmm — KORV (2000) two-elasticity system-GMM estimator.

Strategy:
- Known-value: synthetic DGPs generated by the exact model equations, so the
  GMM moment conditions are exactly zero at the true parameters.
- Properties: output types/shapes, KorvFit/SymCESFit field constraints
  (SE >= 0, Hansen p in [0,1], n_obs == input rows, etc.).
- Edge cases: too few observations returns a non-crashing NaN result;
  degenerate instruments return a graceful NaN SymCESFit.
- Contract-only: functions whose numeric answer depends on optimizer
  convergence are tested for structural contracts (field types, bounds,
  convergence flag) rather than exact point estimates.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from puremacro.korv_gmm import (
    KorvFit,
    SymCESFit,
    _allen_sigma_es,
    _gmm_objective,
    _gmm_objective_2mom,
    _moments,
    _moments_m1m2,
    _moments_symmetric,
    build_inner_nest_aggregators,
    build_usercost_column,
    calibrate_nest_weights,
    fit_korv_country,
    fit_korv_pooled,
    fit_korv_pooled_2moments,
    fit_korv_pooled_usercost,
    fit_sigma_ie_pooled,
    fit_sigma_kl_pooled,
    fit_sigma_su_pooled,
    fit_symmetric_nested_ces_joint,
    fit_symmetric_nested_ces_pooled,
)

RNG = np.random.default_rng(2024)


# ---------------------------------------------------------------------------
# Helpers to build synthetic panels consistent with the KORV moment conditions
# ---------------------------------------------------------------------------

def _make_korv_panel(
    n: int = 80,
    sigma_su: float = 0.7,
    sigma_eu: float = 1.5,
    noise: float = 0.05,
    rng: np.random.Generator | None = None,
) -> pd.DataFrame:
    """Synthetic panel where FOCs hold at (sigma_su, sigma_eu) + small noise.

    The three KORV first-order conditions in log-differences are:
      Δlog(L_s/L_u)     = σ_su * Δlog(w_s/w_u)   + ε1
      Δlog(K_e/L_u)     = σ_eu * Δlog(w_u/P_K)   + ε2
      Δlog(LS_u_share)  = (1-σ_eu) * Δlog(P_K/P_C) + ε3

    We generate the RHS series from N(0,1) draws, compute LHS exactly from
    the FOC, and add small white noise so the GMM estimator faces a nearly-
    identified problem.
    """
    if rng is None:
        rng = np.random.default_rng(42)
    dlog_ws_wu  = rng.standard_normal(n)
    dlog_wu_pk  = rng.standard_normal(n)
    dlog_pk_pc  = rng.standard_normal(n)
    dlog_ls_lu    = -sigma_su       * dlog_ws_wu  + noise * rng.standard_normal(n)
    dlog_ke_lu    = sigma_eu        * dlog_wu_pk  + noise * rng.standard_normal(n)
    dlog_lsushare = (1 - sigma_eu)  * dlog_pk_pc  + noise * rng.standard_normal(n)
    return pd.DataFrame({
        'dlog_ls_lu':    dlog_ls_lu,
        'dlog_ws_wu':    dlog_ws_wu,
        'dlog_ke_lu':    dlog_ke_lu,
        'dlog_wu_pk':    dlog_wu_pk,
        'dlog_lsushare': dlog_lsushare,
        'dlog_pk_pc':    dlog_pk_pc,
        'k_equip_share_inner': np.full(n, 0.4),
    })


def _make_pooled_panel(
    n_countries: int = 4,
    n_per: int = 40,
    sigma_su: float = 0.7,
    sigma_eu: float = 1.5,
    noise: float = 0.05,
    rng: np.random.Generator | None = None,
) -> pd.DataFrame:
    """Multi-country panel suitable for pooled GMM estimators."""
    if rng is None:
        rng = np.random.default_rng(99)
    codes = [f"C{i}" for i in range(n_countries)]
    chunks = []
    for code in codes:
        chunk = _make_korv_panel(n=n_per, sigma_su=sigma_su, sigma_eu=sigma_eu,
                                  noise=noise, rng=rng)
        chunk['code'] = code
        chunks.append(chunk)
    return pd.concat(chunks, ignore_index=True)


# ===========================================================================
# 1. _allen_sigma_es — known analytical formula tests
# ===========================================================================

class TestAllenSigmaEs:
    def test_cd_limit_equal_elasticities(self):
        """When σ_su == σ_eu, the harmonic mean equals both."""
        for s in [0.5, 0.7, 1.2, 2.0]:
            result = _allen_sigma_es(s, s, 0.4)
            assert abs(result - s) < 1e-12, f"expected {s}, got {result}"

    def test_harmonic_between_min_max(self):
        """Harmonic mean must lie strictly between min(σ) and max(σ)."""
        sigma_su, sigma_eu = 0.5, 2.0
        for share in [0.1, 0.3, 0.5, 0.7, 0.9]:
            result = _allen_sigma_es(sigma_su, sigma_eu, share)
            assert min(sigma_su, sigma_eu) < result < max(sigma_su, sigma_eu), (
                f"share={share}: result={result} not strictly between "
                f"{sigma_su} and {sigma_eu}"
            )

    def test_monotone_in_share(self):
        """As equipment share rises toward 1, σ_es approaches σ_eu."""
        sigma_su, sigma_eu = 0.5, 2.0
        shares = np.linspace(0.01, 0.99, 20)
        values = [_allen_sigma_es(sigma_su, sigma_eu, s) for s in shares]
        # When share_e -> 1: harmonic mean = 1/(1/sigma_eu + 0/sigma_su) = sigma_eu
        # When share_e -> 0: harmonic mean -> sigma_su
        assert values[-1] > values[0], "sigma_es should increase with share_e"

    def test_degenerate_share_clipped(self):
        """share values outside (0,1) should be clipped without crashing."""
        # Should not raise; just return a valid float
        result_zero  = _allen_sigma_es(0.5, 1.5, 0.0)
        result_one   = _allen_sigma_es(0.5, 1.5, 1.0)
        result_neg   = _allen_sigma_es(0.5, 1.5, -0.5)
        result_large = _allen_sigma_es(0.5, 1.5, 5.0)
        for val in [result_zero, result_one, result_neg, result_large]:
            assert np.isfinite(val), f"expected finite, got {val}"

    def test_known_value(self):
        """Verify formula: 1 / (0.5/σ_eu + 0.5/σ_su)."""
        sigma_su, sigma_eu, share = 0.5, 2.0, 0.5
        expected = 1.0 / (0.5 / sigma_eu + 0.5 / sigma_su)
        result = _allen_sigma_es(sigma_su, sigma_eu, share)
        assert abs(result - expected) < 1e-12


# ===========================================================================
# 2. _moments — shape and zero-at-true-params test
# ===========================================================================

class TestMoments:
    def test_output_shape(self):
        """_moments must return (n_obs, 3) array."""
        df = _make_korv_panel(n=30)
        dat = {c: df[c].to_numpy() for c in
               ('dlog_ls_lu', 'dlog_ws_wu', 'dlog_ke_lu',
                'dlog_wu_pk', 'dlog_lsushare', 'dlog_pk_pc')}
        theta = np.array([0.7, 1.5])
        out = _moments(theta, dat)
        assert out.shape == (30, 3)

    def test_near_zero_at_true_params(self):
        """With noise=0, mean of moment conditions must be near zero at DGP params."""
        df = _make_korv_panel(n=500, sigma_su=0.7, sigma_eu=1.5, noise=0.0)
        dat = {c: df[c].to_numpy() for c in
               ('dlog_ls_lu', 'dlog_ws_wu', 'dlog_ke_lu',
                'dlog_wu_pk', 'dlog_lsushare', 'dlog_pk_pc')}
        theta_true = np.array([0.7, 1.5])
        g_bar = _moments(theta_true, dat).mean(axis=0)
        # Exact-identification means moments are not identically zero
        # but they should be much smaller than at wrong params
        theta_wrong = np.array([1.5, 0.5])
        g_bar_wrong = _moments(theta_wrong, dat).mean(axis=0)
        assert np.linalg.norm(g_bar) < np.linalg.norm(g_bar_wrong), (
            "Moments at true params should be smaller in norm than at wrong params"
        )


# ===========================================================================
# 3. _moments_m1m2 — shape and structure
# ===========================================================================

class TestMomentsM1M2:
    def test_output_shape(self):
        """_moments_m1m2 must return (n_obs, 2) array."""
        df = _make_korv_panel(n=25)
        dat = {c: df[c].to_numpy() for c in
               ('dlog_ls_lu', 'dlog_ws_wu', 'dlog_ke_lu', 'dlog_wu_pk')}
        out = _moments_m1m2(np.array([0.7, 1.5]), dat)
        assert out.shape == (25, 2)

    def test_first_col_consistent_with_moments(self):
        """First column of _moments_m1m2 equals first column of _moments."""
        n = 40
        df = _make_korv_panel(n=n)
        dat3 = {c: df[c].to_numpy() for c in
                ('dlog_ls_lu', 'dlog_ws_wu', 'dlog_ke_lu',
                 'dlog_wu_pk', 'dlog_lsushare', 'dlog_pk_pc')}
        dat2 = {c: df[c].to_numpy() for c in
                ('dlog_ls_lu', 'dlog_ws_wu', 'dlog_ke_lu', 'dlog_wu_pk')}
        theta = np.array([0.8, 1.2])
        m3 = _moments(theta, dat3)
        m2 = _moments_m1m2(theta, dat2)
        np.testing.assert_allclose(m2[:, 0], m3[:, 0], rtol=1e-12)
        np.testing.assert_allclose(m2[:, 1], m3[:, 1], rtol=1e-12)


# ===========================================================================
# 4. _gmm_objective and _gmm_objective_2mom — scalar, non-negative
# ===========================================================================

class TestGmmObjective:
    def test_returns_scalar_nonneg(self):
        """GMM objective must be a non-negative scalar."""
        df = _make_korv_panel(n=30)
        dat = {c: df[c].to_numpy() for c in
               ('dlog_ls_lu', 'dlog_ws_wu', 'dlog_ke_lu',
                'dlog_wu_pk', 'dlog_lsushare', 'dlog_pk_pc')}
        theta = np.array([0.7, 1.5])
        W = np.eye(3)
        val = _gmm_objective(theta, dat, W)
        assert isinstance(val, float)
        assert val >= 0.0

    def test_2mom_returns_scalar_nonneg(self):
        df = _make_korv_panel(n=30)
        dat = {c: df[c].to_numpy() for c in
               ('dlog_ls_lu', 'dlog_ws_wu', 'dlog_ke_lu', 'dlog_wu_pk')}
        theta = np.array([0.7, 1.5])
        W = np.eye(2)
        val = _gmm_objective_2mom(theta, dat, W)
        assert isinstance(val, float)
        assert val >= 0.0

    def test_identity_weight_equals_quadratic_form(self):
        """With W=I, objective must equal ||g_bar||^2."""
        df = _make_korv_panel(n=40)
        dat = {c: df[c].to_numpy() for c in
               ('dlog_ls_lu', 'dlog_ws_wu', 'dlog_ke_lu',
                'dlog_wu_pk', 'dlog_lsushare', 'dlog_pk_pc')}
        theta = np.array([0.9, 1.1])
        g_bar = _moments(theta, dat).mean(axis=0)
        expected = float(g_bar @ g_bar)
        result = _gmm_objective(theta, dat, np.eye(3))
        assert abs(result - expected) < 1e-14


# ===========================================================================
# 5. fit_korv_country — KorvFit contracts
# ===========================================================================

class TestFitKorvCountry:
    def test_returns_korvfit(self):
        df = _make_korv_panel(n=40)
        result = fit_korv_country(df)
        assert isinstance(result, KorvFit)

    def test_too_few_obs_returns_nan(self):
        """With n < 8 rows, fit must return NaN estimates and converged=False."""
        df = _make_korv_panel(n=5)
        result = fit_korv_country(df)
        assert not result.converged
        assert result.n_obs == 5
        assert np.isnan(result.sigma_su)
        assert np.isnan(result.sigma_eu)
        assert result.hansen_J is None
        assert result.hansen_p is None

    def test_n_obs_matches_input(self):
        n = 50
        df = _make_korv_panel(n=n)
        result = fit_korv_country(df)
        assert result.n_obs == n

    def test_n_country_is_one(self):
        df = _make_korv_panel(n=40)
        result = fit_korv_country(df)
        assert result.n_country == 1

    def test_no_hansen_J(self):
        """Per-country fit is just-identified so hansen_J must be None."""
        df = _make_korv_panel(n=40)
        result = fit_korv_country(df)
        assert result.hansen_J is None
        assert result.hansen_p is None

    def test_se_nonnegative(self):
        df = _make_korv_panel(n=40)
        result = fit_korv_country(df)
        assert result.se_sigma_su >= 0 or np.isnan(result.se_sigma_su)
        assert result.se_sigma_eu >= 0 or np.isnan(result.se_sigma_eu)

    def test_sigma_es_between_sigma_su_and_sigma_eu(self):
        """sigma_es must lie in the convex hull of (sigma_su, sigma_eu)."""
        df = _make_korv_panel(n=60, noise=0.01)
        result = fit_korv_country(df)
        if np.isfinite(result.sigma_su) and np.isfinite(result.sigma_eu):
            lo = min(result.sigma_su, result.sigma_eu)
            hi = max(result.sigma_su, result.sigma_eu)
            # Add a buffer because it's a harmonic mean, strictly inside
            assert lo <= result.sigma_es <= hi, (
                f"sigma_es={result.sigma_es} outside [{lo}, {hi}]"
            )

    def test_default_share_when_column_missing(self):
        """Without 'k_equip_share_inner', should default to share=0.5."""
        df = _make_korv_panel(n=40)
        df_nosha = df.drop(columns=['k_equip_share_inner'])
        result = fit_korv_country(df_nosha)
        # sigma_es at share=0.5 is harmonic mean of sigma_su, sigma_eu
        expected_sigma_es = _allen_sigma_es(result.sigma_su, result.sigma_eu, 0.5)
        assert abs(result.sigma_es - expected_sigma_es) < 1e-8

    @pytest.mark.slow
    def test_recovers_true_params_approx(self):
        """Near-zero noise: estimates should be close to DGP parameters."""
        rng = np.random.default_rng(123)
        df = _make_korv_panel(n=200, sigma_su=0.7, sigma_eu=1.5, noise=0.001, rng=rng)
        result = fit_korv_country(df)
        assert abs(result.sigma_su - 0.7) < 0.15, (
            f"sigma_su={result.sigma_su:.3f}, expected ~0.7"
        )
        assert abs(result.sigma_eu - 1.5) < 0.30, (
            f"sigma_eu={result.sigma_eu:.3f}, expected ~1.5"
        )


# ===========================================================================
# 6. fit_korv_pooled — pooled GMM with Hansen J
# ===========================================================================

class TestFitKorvPooled:
    def test_returns_korvfit(self):
        df = _make_pooled_panel()
        result = fit_korv_pooled(df)
        assert isinstance(result, KorvFit)

    def test_n_obs_and_n_country_match(self):
        n_countries, n_per = 3, 30
        df = _make_pooled_panel(n_countries=n_countries, n_per=n_per)
        result = fit_korv_pooled(df)
        assert result.n_obs == n_countries * n_per
        assert result.n_country == n_countries

    def test_hansen_j_present_and_nonneg(self):
        """Pooled GMM has 1 over-identifying restriction so J must exist."""
        df = _make_pooled_panel()
        result = fit_korv_pooled(df)
        assert result.hansen_J is not None
        assert result.hansen_J >= 0.0

    def test_hansen_p_in_unit_interval(self):
        df = _make_pooled_panel()
        result = fit_korv_pooled(df)
        assert 0.0 <= result.hansen_p <= 1.0

    def test_obj_value_nonneg(self):
        df = _make_pooled_panel()
        result = fit_korv_pooled(df)
        assert result.obj_value >= 0.0

    @pytest.mark.slow
    def test_recovers_true_params_approx_pooled(self):
        """Low-noise pooled panel: estimates near DGP parameters."""
        rng = np.random.default_rng(55)
        df = _make_pooled_panel(n_countries=5, n_per=100,
                                 sigma_su=0.7, sigma_eu=1.5, noise=0.005, rng=rng)
        result = fit_korv_pooled(df)
        assert abs(result.sigma_su - 0.7) < 0.20
        assert abs(result.sigma_eu - 1.5) < 0.35

    def test_default_share_when_column_missing(self):
        """Without 'k_equip_share_inner', fit_korv_pooled defaults to share=0.5."""
        df = _make_pooled_panel()
        df_nosha = df.drop(columns=['k_equip_share_inner'])
        result = fit_korv_pooled(df_nosha)
        expected = _allen_sigma_es(result.sigma_su, result.sigma_eu, 0.5)
        assert abs(result.sigma_es - expected) < 1e-8


# ===========================================================================
# 7. fit_korv_pooled_2moments — just-identified, no Hansen J
# ===========================================================================

class TestFitKorvPooled2Moments:
    def test_returns_korvfit(self):
        df = _make_pooled_panel()
        result = fit_korv_pooled_2moments(df)
        assert isinstance(result, KorvFit)

    def test_hansen_j_is_none(self):
        """Just-identified (2 moments, 2 params): Hansen J must be None."""
        df = _make_pooled_panel()
        result = fit_korv_pooled_2moments(df)
        assert result.hansen_J is None
        assert result.hansen_p is None

    def test_n_obs_matches(self):
        n_countries, n_per = 4, 25
        df = _make_pooled_panel(n_countries=n_countries, n_per=n_per)
        result = fit_korv_pooled_2moments(df)
        assert result.n_obs == n_countries * n_per

    def test_se_nonneg(self):
        df = _make_pooled_panel()
        result = fit_korv_pooled_2moments(df)
        for se in (result.se_sigma_su, result.se_sigma_eu):
            assert se >= 0 or np.isnan(se)

    def test_default_share_when_column_missing(self):
        """Without 'k_equip_share_inner', pooled_2moments defaults to share=0.5."""
        df = _make_pooled_panel()
        df_nosha = df.drop(columns=['k_equip_share_inner'])
        result = fit_korv_pooled_2moments(df_nosha)
        # sigma_es at share=0.5 is harmonic mean
        expected = _allen_sigma_es(result.sigma_su, result.sigma_eu, 0.5)
        assert abs(result.sigma_es - expected) < 1e-8


# ===========================================================================
# 8. build_usercost_column — Hall-Jorgenson user cost
# ===========================================================================

class TestBuildUsercostColumn:
    def _make_price_panel(self, n_per: int = 20) -> pd.DataFrame:
        rng = np.random.default_rng(7)
        codes = ['US', 'DE']
        rows = []
        for code in codes:
            p_k = np.cumprod(1 + 0.01 * rng.standard_normal(n_per))
            for t in range(n_per):
                rows.append({'code': code, 'year': 2000 + t, 'p_k': p_k[t]})
        return pd.DataFrame(rows)

    def test_returns_series_aligned_to_panel(self):
        panel = self._make_price_panel()
        result = build_usercost_column(panel)
        assert isinstance(result, pd.Series)
        assert len(result) == len(panel)
        assert result.name == 'log_r_e'

    def test_last_obs_per_country_is_nan(self):
        """Forward diff: last observation within each country must be NaN."""
        panel = self._make_price_panel(n_per=15)
        result = build_usercost_column(panel)
        panel_with_uc = panel.copy()
        panel_with_uc['log_r_e'] = result.values
        for code in ['US', 'DE']:
            last_val = panel_with_uc[panel_with_uc['code'] == code]['log_r_e'].iloc[-1]
            assert np.isnan(last_val), (
                f"Last obs for {code} should be NaN (forward diff undefined)"
            )

    def test_with_r_col(self):
        """Passing r_col uses per-row interest rate."""
        panel = self._make_price_panel()
        panel['r_rate'] = 0.04
        result = build_usercost_column(panel, r_col='r_rate')
        result_default = build_usercost_column(panel, r_bar=0.04)
        # Should be identical since r_rate == r_bar everywhere
        mask = ~(result.isna() | result_default.isna())
        np.testing.assert_allclose(
            result[mask].to_numpy(), result_default[mask].to_numpy(), rtol=1e-10
        )

    def test_large_depreciation_increases_usercost(self):
        """Higher δ_e raises the user cost (cap_factor = r + δ - E[ΔlogP_K])."""
        panel = self._make_price_panel()
        uc_low  = build_usercost_column(panel, delta_e=0.05)
        uc_high = build_usercost_column(panel, delta_e=0.20)
        mask = ~(uc_low.isna() | uc_high.isna())
        # Higher depreciation → higher user cost → higher log_r_e
        assert (uc_high[mask] > uc_low[mask]).all(), (
            "Higher δ_e should increase log user cost"
        )


# ===========================================================================
# 9. fit_korv_pooled_usercost — structural contract
# ===========================================================================

class TestFitKorvPooledUsercost:
    def _make_usercost_panel(self) -> pd.DataFrame:
        rng = np.random.default_rng(11)
        n_per = 40
        codes = ['US', 'DE', 'FR', 'JP']
        chunks = []
        for code in codes:
            p_k  = np.cumprod(1 + 0.005 * rng.standard_normal(n_per))
            w_u  = np.cumprod(1 + 0.01  * rng.standard_normal(n_per))
            base = _make_korv_panel(n=n_per, rng=rng)
            base['code']  = code
            base['year']  = np.arange(1980, 1980 + n_per)
            base['p_k']   = p_k
            base['w_u']   = w_u
            base['p_c']   = np.ones(n_per)
            chunks.append(base)
        df = pd.concat(chunks, ignore_index=True)
        return df.sort_values(['code', 'year']).reset_index(drop=True)

    @pytest.mark.slow
    def test_returns_korvfit(self):
        panel = self._make_usercost_panel()
        result = fit_korv_pooled_usercost(panel)
        assert isinstance(result, KorvFit)

    @pytest.mark.slow
    def test_hansen_j_present(self):
        """User-cost variant retains 3 moments so J must be present."""
        panel = self._make_usercost_panel()
        result = fit_korv_pooled_usercost(panel)
        # May fail to converge but should still return a KorvFit
        if result.n_obs > 0:
            # J can be None if too few clean rows remain; just check type
            if result.hansen_J is not None:
                assert result.hansen_J >= 0.0
                assert 0.0 <= result.hansen_p <= 1.0


# ===========================================================================
# 10. calibrate_nest_weights — CES weight calibration
# ===========================================================================

class TestCalibrateNestWeights:
    def _make_panel(self, base_year: int = 2000) -> pd.DataFrame:
        rng = np.random.default_rng(13)
        codes = ['US', 'DE', 'FR']
        rows = []
        for code in codes:
            for yr in range(1998, 2005):
                p_num = 1.0 + 0.1 * rng.random()
                p_den = 1.0 + 0.1 * rng.random()
                share = 0.3 + 0.1 * rng.random()
                rows.append({
                    'code': code, 'year': yr,
                    'p_num': p_num, 'p_den': p_den, 'share': share,
                })
        return pd.DataFrame(rows)

    def test_returns_dataframe_with_weight_col(self):
        panel = self._make_panel()
        result = calibrate_nest_weights(
            panel, sigma=1.5, share_col='share',
            p_num_col='p_num', p_den_col='p_den', base_year=2000,
        )
        assert isinstance(result, pd.DataFrame)
        assert 'alpha_c' in result.columns

    def test_cobb_douglas_limit(self):
        """At σ = 1, weight equals base-year cost share (no price correction)."""
        panel = self._make_panel(base_year=2000)
        result = calibrate_nest_weights(
            panel, sigma=1.0, share_col='share',
            p_num_col='p_num', p_den_col='p_den', base_year=2000,
        )
        # For base year rows, alpha_c == share exactly
        base_rows = result[result['year'] == 2000]
        for _, row in base_rows.iterrows():
            assert abs(row['alpha_c'] - row['share']) < 1e-12, (
                f"At σ=1: alpha_c={row['alpha_c']:.6f} != share={row['share']:.6f}"
            )

    def test_missing_base_year_gives_nan(self):
        """Country missing from base year should get NaN weight."""
        panel = self._make_panel(base_year=2000)
        # Use a year not in the panel as base_year
        result = calibrate_nest_weights(
            panel, sigma=1.5, share_col='share',
            p_num_col='p_num', p_den_col='p_den', base_year=1990,
        )
        assert result['alpha_c'].isna().all(), (
            "base_year=1990 not in panel → all weights should be NaN"
        )

    def test_weight_col_name_respected(self):
        panel = self._make_panel()
        result = calibrate_nest_weights(
            panel, sigma=1.2, share_col='share',
            p_num_col='p_num', p_den_col='p_den', base_year=2000,
            weight_col='gamma_c',
        )
        assert 'gamma_c' in result.columns
        assert 'alpha_c' not in result.columns


# ===========================================================================
# 11. build_inner_nest_aggregators — CES quantity/price duals
# ===========================================================================

class TestBuildInnerNestAggregators:
    def _make_panel(self, sigma_ie: float = 1.5, sigma_su: float = 0.7,
                    n: int = 20) -> pd.DataFrame:
        rng = np.random.default_rng(17)
        data = {
            'code': ['US'] * n,
            'K_e':  1.0 + 0.1 * rng.random(n),
            'K_i':  1.0 + 0.1 * rng.random(n),
            'L_s':  1.0 + 0.1 * rng.random(n),
            'L_u':  1.0 + 0.1 * rng.random(n),
            'P_e':  1.0 + 0.05 * rng.random(n),
            'P_i':  1.0 + 0.05 * rng.random(n),
            'w_s':  1.0 + 0.05 * rng.random(n),
            'w_u':  1.0 + 0.05 * rng.random(n),
            'alpha_c': 0.4 * np.ones(n),
            'gamma_c': 0.6 * np.ones(n),
        }
        return pd.DataFrame(data)

    def test_returns_df_with_required_cols(self):
        df = self._make_panel()
        result = build_inner_nest_aggregators(df, sigma_ie=1.5, sigma_su=0.7)
        for col in ('K_agg', 'L_agg', 'P_K', 'w'):
            assert col in result.columns, f"missing column {col}"

    def test_quantities_positive(self):
        df = self._make_panel()
        result = build_inner_nest_aggregators(df, sigma_ie=1.5, sigma_su=0.7)
        assert (result['K_agg'] > 0).all()
        assert (result['L_agg'] > 0).all()
        assert (result['P_K'] > 0).all()
        assert (result['w'] > 0).all()

    def test_cobb_douglas_limit(self):
        """At σ → 1, CES aggregator reduces to geometric mean."""
        df = self._make_panel()
        alpha = 0.4
        gamma = 0.6
        result = build_inner_nest_aggregators(df, sigma_ie=1.0, sigma_su=1.0)
        # K_agg = K_e^alpha * K_i^(1-alpha)
        expected_K = (df['K_e'] ** alpha) * (df['K_i'] ** (1 - alpha))
        np.testing.assert_allclose(
            result['K_agg'].to_numpy(), expected_K.to_numpy(), rtol=1e-9
        )
        # L_agg = L_s^gamma * L_u^(1-gamma)
        expected_L = (df['L_s'] ** gamma) * (df['L_u'] ** (1 - gamma))
        np.testing.assert_allclose(
            result['L_agg'].to_numpy(), expected_L.to_numpy(), rtol=1e-9
        )

    def test_does_not_modify_input(self):
        df = self._make_panel()
        original_cols = set(df.columns)
        _ = build_inner_nest_aggregators(df, sigma_ie=1.5, sigma_su=0.7)
        assert set(df.columns) == original_cols, "input DataFrame should not be modified"


# ===========================================================================
# 12. fit_sigma_su_pooled — 2SLS block A contract
# ===========================================================================

class TestFitSigmaSuPooled:
    def _make_panel(self, n_per: int = 50, beta_true: float = 0.8) -> pd.DataFrame:
        """2SLS DGP: y = beta * x + eps; z is instrument correlated with x."""
        rng = np.random.default_rng(21)
        codes = ['A', 'B', 'C']
        chunks = []
        for code in codes:
            z    = rng.standard_normal(n_per)
            x    = 0.8 * z + 0.2 * rng.standard_normal(n_per)
            y    = -beta_true * x + 0.1 * rng.standard_normal(n_per)
            df_c = pd.DataFrame({
                'code': code,
                'dlog_ls_lu': y,
                'dlog_ws_wu': x,
                'dlog_ns_nu': z,
            })
            chunks.append(df_c)
        return pd.concat(chunks, ignore_index=True)

    def test_returns_sym_ces_fit(self):
        panel = self._make_panel()
        result = fit_sigma_su_pooled(panel)
        assert isinstance(result, SymCESFit)

    def test_sigma_su_populated_others_nan(self):
        panel = self._make_panel()
        result = fit_sigma_su_pooled(panel)
        assert np.isfinite(result.sigma_su)
        assert np.isnan(result.sigma_kl)
        assert np.isnan(result.sigma_ie)

    def test_converged_true(self):
        panel = self._make_panel()
        result = fit_sigma_su_pooled(panel)
        assert result.converged is True

    def test_hansen_j_is_none(self):
        """Single-equation 2SLS is just-identified."""
        panel = self._make_panel()
        result = fit_sigma_su_pooled(panel)
        assert result.hansen_J is None

    def test_recovers_true_beta(self):
        """2SLS should recover the true slope from a standard IV DGP."""
        beta_true = 0.8
        panel = self._make_panel(n_per=200, beta_true=beta_true)
        result = fit_sigma_su_pooled(panel)
        assert abs(result.sigma_su - beta_true) < 0.15, (
            f"sigma_su={result.sigma_su:.3f}, expected ~{beta_true}"
        )

    def test_degenerate_instrument_returns_nan(self):
        """Zero-variance instrument: 2SLS should return NaN sigma_su, converged=False."""
        rng = np.random.default_rng(29)
        codes = ['A', 'B']
        rows = []
        for code in codes:
            for _ in range(30):
                rows.append({
                    'code': code,
                    'dlog_ls_lu': rng.standard_normal(),
                    'dlog_ws_wu': rng.standard_normal(),
                    'dlog_ns_nu': 0.0,  # zero variance → degenerate
                })
        panel = pd.DataFrame(rows)
        result = fit_sigma_su_pooled(panel)
        assert np.isnan(result.sigma_su)
        assert result.converged is False


# ===========================================================================
# 13. fit_sigma_ie_pooled — FE-OLS block B contract
# ===========================================================================

class TestFitSigmaIePooled:
    def _make_panel(self, n_per: int = 50, beta_true: float = 1.2) -> pd.DataFrame:
        rng = np.random.default_rng(33)
        codes = ['X', 'Y', 'Z']
        chunks = []
        for code in codes:
            x = rng.standard_normal(n_per)
            y = beta_true * x + 0.1 * rng.standard_normal(n_per)
            chunks.append(pd.DataFrame({
                'code': code,
                'dlog_ki_ke': y,
                'dlog_re_ri': x,
            }))
        return pd.concat(chunks, ignore_index=True)

    def test_returns_sym_ces_fit(self):
        panel = self._make_panel()
        result = fit_sigma_ie_pooled(panel)
        assert isinstance(result, SymCESFit)

    def test_sigma_ie_populated_others_nan(self):
        panel = self._make_panel()
        result = fit_sigma_ie_pooled(panel)
        assert np.isfinite(result.sigma_ie)
        assert np.isnan(result.sigma_kl)
        assert np.isnan(result.sigma_su)

    def test_recovers_true_beta(self):
        """FE-OLS should recover the true slope under exogeneity."""
        beta_true = 1.2
        panel = self._make_panel(n_per=300, beta_true=beta_true)
        result = fit_sigma_ie_pooled(panel)
        assert abs(result.sigma_ie - beta_true) < 0.15, (
            f"sigma_ie={result.sigma_ie:.3f}, expected ~{beta_true}"
        )

    def test_degenerate_rhs_returns_nan(self):
        """Zero-variance RHS: OLS slope is undefined → NaN, converged=False."""
        codes = ['P', 'Q']
        rows = []
        rng = np.random.default_rng(37)
        for code in codes:
            for _ in range(20):
                rows.append({
                    'code': code,
                    'dlog_ki_ke': rng.standard_normal(),
                    'dlog_re_ri': 0.0,
                })
        panel = pd.DataFrame(rows)
        result = fit_sigma_ie_pooled(panel)
        assert np.isnan(result.sigma_ie)
        assert result.converged is False


# ===========================================================================
# 14. _moments_symmetric — shape test
# ===========================================================================

class TestMomentsSymmetric:
    def test_output_shape(self):
        """_moments_symmetric must return (n_obs, 4) for 3-param system."""
        n = 30
        rng = np.random.default_rng(41)
        dat = {
            'dlog_ls_lu':  rng.standard_normal(n),
            'dlog_ws_wu':  rng.standard_normal(n),
            'dlog_ki_ke':  rng.standard_normal(n),
            'dlog_re_ri':  rng.standard_normal(n),
            'dlog_k_l':    rng.standard_normal(n),
            'dlog_w_r':    rng.standard_normal(n),
            'dlog_ls':     rng.standard_normal(n),
            'dlog_pk_pc':  rng.standard_normal(n),
            'z_su':        rng.standard_normal(n),
            'z_kl':        rng.standard_normal(n),
        }
        theta = np.array([1.0, 0.6, 0.7])
        out = _moments_symmetric(theta, dat)
        assert out.shape == (n, 4)


# ===========================================================================
# 15. fit_sigma_kl_pooled — Block C contract
# ===========================================================================

class TestFitSigmaKlPooled:
    def _make_panel_kl(self, n_per: int = 60, sigma_kl_true: float = 1.0) -> pd.DataFrame:
        rng = np.random.default_rng(43)
        codes = ['A', 'B', 'C', 'D']
        chunks = []
        for code in codes:
            # m3: dlog_k_l = sigma_kl * dlog_w_r + e3
            dlog_w_r  = rng.standard_normal(n_per)
            dlog_k_l  = sigma_kl_true * dlog_w_r + 0.1 * rng.standard_normal(n_per)
            # m4: dlog_ls = (1 - sigma_kl) * dlog_pk_pc + e4
            dlog_pk_pc = rng.standard_normal(n_per)
            dlog_ls    = (1 - sigma_kl_true) * dlog_pk_pc + 0.1 * rng.standard_normal(n_per)
            # Instrument for m4
            z_kl = dlog_pk_pc + 0.1 * rng.standard_normal(n_per)
            chunks.append(pd.DataFrame({
                'code': code,
                'dlog_k_l': dlog_k_l,
                'dlog_w_r': dlog_w_r,
                'dlog_ls': dlog_ls,
                'dlog_pk_pc': dlog_pk_pc,
                'z_kl': z_kl,
            }))
        return pd.concat(chunks, ignore_index=True)

    @pytest.mark.slow
    def test_returns_sym_ces_fit(self):
        panel = self._make_panel_kl()
        result = fit_sigma_kl_pooled(panel, iv_col='z_kl')
        assert isinstance(result, SymCESFit)

    @pytest.mark.slow
    def test_sigma_kl_populated_others_nan(self):
        panel = self._make_panel_kl()
        result = fit_sigma_kl_pooled(panel, iv_col='z_kl')
        assert np.isfinite(result.sigma_kl)
        assert np.isnan(result.sigma_ie)
        assert np.isnan(result.sigma_su)

    @pytest.mark.slow
    def test_hansen_j_present(self):
        panel = self._make_panel_kl()
        result = fit_sigma_kl_pooled(panel, iv_col='z_kl')
        assert result.hansen_J is not None
        assert result.hansen_J >= 0.0
        assert 0.0 <= result.hansen_p <= 1.0

    @pytest.mark.slow
    def test_recovers_true_sigma_kl(self):
        """Should recover σ_KL=1.0 from a consistent DGP."""
        sigma_kl_true = 1.0
        panel = self._make_panel_kl(n_per=200, sigma_kl_true=sigma_kl_true)
        result = fit_sigma_kl_pooled(panel, iv_col='z_kl')
        assert abs(result.sigma_kl - sigma_kl_true) < 0.30, (
            f"sigma_kl={result.sigma_kl:.3f}, expected ~{sigma_kl_true}"
        )


# ===========================================================================
# 16. fit_symmetric_nested_ces_pooled — sequential estimator contract
# ===========================================================================

class TestFitSymmetricNestedCesPooled:
    def _make_full_panel(self) -> pd.DataFrame:
        """Panel with all columns required by the three sub-blocks."""
        rng = np.random.default_rng(51)
        n_per = 60
        codes = ['A', 'B', 'C', 'D']
        chunks = []
        for code in codes:
            n = n_per
            df_c = pd.DataFrame({
                'code': code,
                # Block A columns
                'dlog_ls_lu':  rng.standard_normal(n),
                'dlog_ws_wu':  rng.standard_normal(n),
                'dlog_ns_nu':  rng.standard_normal(n),
                # Block B columns
                'dlog_ki_ke':  rng.standard_normal(n),
                'dlog_re_ri':  rng.standard_normal(n),
                # Block C columns
                'dlog_k_l':    rng.standard_normal(n),
                'dlog_w_r':    rng.standard_normal(n),
                'dlog_ls':     rng.standard_normal(n),
                'dlog_pk_pc':  rng.standard_normal(n),
                'iv_kl':       rng.standard_normal(n),
            })
            chunks.append(df_c)
        return pd.concat(chunks, ignore_index=True)

    @pytest.mark.slow
    def test_returns_sym_ces_fit(self):
        panel = self._make_full_panel()
        result = fit_symmetric_nested_ces_pooled(panel, iv_kl='iv_kl')
        assert isinstance(result, SymCESFit)

    @pytest.mark.slow
    def test_all_elasticities_populated(self):
        panel = self._make_full_panel()
        result = fit_symmetric_nested_ces_pooled(panel, iv_kl='iv_kl')
        assert np.isfinite(result.sigma_kl)
        assert np.isfinite(result.sigma_ie)
        assert np.isfinite(result.sigma_su)

    @pytest.mark.slow
    def test_hansen_j_from_block_c(self):
        """Sequential estimator inherits J from Block C."""
        panel = self._make_full_panel()
        result = fit_symmetric_nested_ces_pooled(panel, iv_kl='iv_kl')
        if result.hansen_J is not None:
            assert result.hansen_J >= 0.0
            assert 0.0 <= result.hansen_p <= 1.0


# ===========================================================================
# 17. fit_symmetric_nested_ces_joint — Block D contract
# ===========================================================================

class TestFitSymmetricNestedCesJoint:
    def _make_full_panel(self) -> pd.DataFrame:
        rng = np.random.default_rng(61)
        n_per = 50
        codes = ['A', 'B', 'C', 'D']
        chunks = []
        for code in codes:
            n = n_per
            df_c = pd.DataFrame({
                'code': code,
                'dlog_ls_lu':  rng.standard_normal(n),
                'dlog_ws_wu':  rng.standard_normal(n),
                'dlog_ki_ke':  rng.standard_normal(n),
                'dlog_re_ri':  rng.standard_normal(n),
                'dlog_k_l':    rng.standard_normal(n),
                'dlog_w_r':    rng.standard_normal(n),
                'dlog_ls':     rng.standard_normal(n),
                'dlog_pk_pc':  rng.standard_normal(n),
                'iv_su':       rng.standard_normal(n),
                'iv_kl':       rng.standard_normal(n),
            })
            chunks.append(df_c)
        return pd.concat(chunks, ignore_index=True)

    @pytest.mark.slow
    def test_returns_sym_ces_fit(self):
        panel = self._make_full_panel()
        result = fit_symmetric_nested_ces_joint(panel, iv_su='iv_su', iv_kl='iv_kl')
        assert isinstance(result, SymCESFit)

    @pytest.mark.slow
    def test_all_elasticities_populated(self):
        panel = self._make_full_panel()
        result = fit_symmetric_nested_ces_joint(panel, iv_su='iv_su', iv_kl='iv_kl')
        assert np.isfinite(result.sigma_kl)
        assert np.isfinite(result.sigma_ie)
        assert np.isfinite(result.sigma_su)

    @pytest.mark.slow
    def test_hansen_j_present(self):
        """Joint estimator has 1 over-identifying restriction."""
        panel = self._make_full_panel()
        result = fit_symmetric_nested_ces_joint(panel, iv_su='iv_su', iv_kl='iv_kl')
        assert result.hansen_J is not None
        assert result.hansen_J >= 0.0
        assert 0.0 <= result.hansen_p <= 1.0

    @pytest.mark.slow
    def test_n_obs_and_n_country(self):
        panel = self._make_full_panel()
        result = fit_symmetric_nested_ces_joint(panel, iv_su='iv_su', iv_kl='iv_kl')
        assert result.n_obs > 0
        assert result.n_country == 4


# ===========================================================================
# 18. KorvFit and SymCESFit dataclasses — immutability and field presence
# ===========================================================================

class TestDataclasses:
    def test_korvfit_fields_accessible(self):
        fit = KorvFit(
            sigma_su=0.7, sigma_eu=1.5, sigma_es=0.9,
            se_sigma_su=0.1, se_sigma_eu=0.2,
            obj_value=0.001, hansen_J=1.5, hansen_p=0.22,
            n_obs=100, n_country=3, converged=True,
        )
        assert fit.sigma_su == 0.7
        assert fit.sigma_eu == 1.5
        assert fit.n_obs == 100

    def test_korvfit_frozen(self):
        fit = KorvFit(
            sigma_su=0.7, sigma_eu=1.5, sigma_es=0.9,
            se_sigma_su=0.1, se_sigma_eu=0.2,
            obj_value=0.001, hansen_J=None, hansen_p=None,
            n_obs=100, n_country=1, converged=True,
        )
        with pytest.raises((AttributeError, TypeError)):
            fit.sigma_su = 999.0  # type: ignore[misc]

    def test_sym_ces_fit_fields_accessible(self):
        fit = SymCESFit(
            sigma_kl=1.0, sigma_ie=0.6, sigma_su=0.7,
            se_sigma_kl=0.1, se_sigma_ie=0.05, se_sigma_su=0.08,
            obj_value=0.0, hansen_J=0.5, hansen_p=0.48,
            n_obs=200, n_country=4, converged=True,
        )
        assert fit.sigma_kl == 1.0
        assert fit.n_country == 4

    def test_sym_ces_fit_frozen(self):
        fit = SymCESFit(
            sigma_kl=1.0, sigma_ie=0.6, sigma_su=0.7,
            se_sigma_kl=0.1, se_sigma_ie=0.05, se_sigma_su=0.08,
            obj_value=0.0, hansen_J=None, hansen_p=None,
            n_obs=200, n_country=4, converged=True,
        )
        with pytest.raises((AttributeError, TypeError)):
            fit.sigma_kl = 999.0  # type: ignore[misc]
