"""Independent counterexamples from the September 2026 structural-model review.

Oracles are closed-form policies, accounting identities, and public failure
contracts, rather than goldens generated by the solver under test.
"""
from dataclasses import replace
import numpy as np
import pytest

from puremacro.dsge import load_mod
from puremacro.dsge.parity import verify_dynare_parity
from puremacro.dsge.pruning import canonical_growth_2nd_order
from puremacro.trade import solve_trade_equilibrium
from puremacro.trade.data import generate_synthetic_mrio, package_mrio_to_calibration_result


@pytest.fixture(scope="module")
def calibration():
    return package_mrio_to_calibration_result(generate_synthetic_mrio("wiod", custom_c=2, custom_s=2))


@pytest.mark.parametrize("rho", [.5, .8])
@pytest.mark.parametrize("equation", ["cubic", "lead_cubic", "quadratic_feedback"])
def test_third_order_risk_slopes_closed_form(rho, equation):
    beta, eta, sd = .95, .3, .1
    if equation == "cubic":
        rhs = "x^3"
        A = 1 / (1 - beta * rho**3)
        B = 3 * beta * A * rho * sd**2 / (1 - beta * rho)
    elif equation == "lead_cubic":
        rhs = "x(+1)^3+eta*x(+1)^2*x"
        A = (rho**3 + eta * rho**2) / (1 - beta * rho**3)
        B = (3 * beta * A * rho + 3 * rho + eta) * sd**2 / (1 - beta * rho)
    else:
        rhs = "x^2+eta*x*y(+1)"
        A = 1 / (1 - beta * rho**2)
        C = beta * A / (1 - beta)
        D = eta * A * rho**2 / (1 - beta * rho**3)
        B = (3 * beta * D * rho + eta * (A + C)) * sd**2 / (1 - beta * rho)
    sol = load_mod(f"""
        var x y; varexo e; parameters rho beta eta;
        rho={rho}; beta={beta}; eta={eta};
        model; x=rho*x(-1)+e; y=beta*y(+1)+{rhs}; end;
        initval; x=0;y=0;end; shocks;var e;stderr {sd};end;
    """, order=3)
    np.testing.assert_allclose(sol.ghxss[1, 0], 2 * B * rho, rtol=1e-10, atol=1e-12)
    np.testing.assert_allclose(sol.ghuss[1, 0], 2 * B, rtol=1e-10, atol=1e-12)


def test_third_order_correlated_shocks_and_multiple_states():
    rho, beta = .7, .95
    cov = np.array([[.01, .004], [.004, .04]])
    sol = load_mod("""
        var x z y; varexo e v; parameters rho beta; rho=.7;beta=.95;
        model; x=rho*x(-1)+e;z=rho*z(-1)+v;y=beta*y(+1)+(x+2*z)^3;end;
        initval;x=0;z=0;y=0;end;
        shocks;var e;stderr .1;var v;stderr .2;corr e,v=.2;end;
    """, order=3)
    loading = np.array([1., 2.])
    B = 3 * beta * rho * (loading @ cov @ loading) / ((1-beta*rho**3)*(1-beta*rho))
    np.testing.assert_allclose(sol.ghxss[2], 2 * B * rho * loading, rtol=1e-10)
    np.testing.assert_allclose(sol.ghuss[2], 2 * B * loading, rtol=1e-10)


@pytest.mark.parametrize("field", ["ys", "ghxu", "ghuu", "ghxx", "ghs2", "ghx", "ghu"])
def test_parity_checks_every_second_order_field(field):
    dr = canonical_growth_2nd_order().decision_rules()
    bad = replace(dr, **{field: getattr(dr, field) + 1000})
    result = verify_dynare_parity(dr, bad, order=2)
    assert not result.passed
    assert result.max_dev_dr >= 1000 - 1e-8


def test_parity_nonfinite_is_unavailable():
    dr = canonical_growth_2nd_order().decision_rules()
    result = verify_dynare_parity(dr, replace(dr, ghxu=dr.ghxu * np.nan), order=2)
    assert not result.passed
    assert result.details["status"] == "UNAVAILABLE"


def test_projection_cannot_converge_to_nonzero_constant_residual():
    from puremacro.vfi import CollocationProblem
    sol = CollocationProblem(domain=(1., 2.), orders=3, method="euler",
        euler_residual_fn=lambda policy, s, params: np.ones_like(s), options={"tol": 1e-10}).solve()
    assert not sol.converged
    assert sol.residual_norm == 1.0


@pytest.mark.parametrize("productivity", [1., 2.])
def test_collocation_value_uses_model_productivity(productivity):
    from puremacro.vfi import CollocationProblem
    alpha, beta = .36, .96
    k = (alpha * beta * productivity)**(1 / (1-alpha))
    c = productivity * k**alpha - k
    sol = CollocationProblem(domain=(.5*k, 1.5*k), orders=13, beta=beta,
        params={"alpha": alpha, "delta": 1., "sigma": 1., "z": productivity}).solve()
    assert abs(sol.value(k) - np.log(c) / (1-beta)) < 1e-5


@pytest.mark.parametrize("sigma", [0., 1., 2.])
def test_reported_trade_flows_satisfy_demand_equations(calibration, sigma):
    from puremacro.trade.equilibrium import _get_ces_weights
    c = calibration
    tau = np.ones((4, 2, 2)); tau[2:, :, 0] = 1.2
    sol = solve_trade_equilibrium(c, tau=tau, sigma=sigma, tol=1e-9, max_iter=100)
    assert sol.converged
    _, omega = _get_ces_weights(c)
    p = sol.p_sol.flatten(order="F")[:, None, None] * tau
    P = np.exp(np.sum(omega * np.log(p), axis=0)) if sigma == 1 else np.sum(omega*p**(1-sigma), axis=0)**(1/(1-sigma))
    expected = c.a * sol.y_sol * (P[None] / p)**sigma
    np.testing.assert_allclose(sol.intermediate_flows, expected.reshape((2, 2, 2, 2), order="F"), atol=1e-7)


def test_pac_preserves_final_demand_tariff(calibration):
    kwargs = dict(tau_fd=np.array([.2, 0.]), tol=1e-9)
    newton = solve_trade_equilibrium(calibration, **kwargs)
    pac = solve_trade_equilibrium(calibration, method="keller_pac", max_steps=2, **kwargs)
    assert newton.converged and pac.converged
    np.testing.assert_allclose(pac.tariffs, newton.tariffs, atol=1e-7)
    np.testing.assert_allclose(pac.x_sol, newton.x_sol, atol=1e-7)


@pytest.mark.parametrize("name", ["load_figaro", "load_exiobase", "load_wiod", "load_eora", "load_oecd_icio_granular"])
def test_mrio_requires_explicit_synthetic_opt_in(name):
    from puremacro.trade import data
    loader = getattr(data, name)
    with pytest.raises(FileNotFoundError):
        loader(file_path="/definitely/missing.csv")
    with pytest.raises(ValueError, match="synthetic"):
        loader(custom_c=2, custom_s=2)
    c = loader(custom_c=2, custom_s=2, fallback_to_synthetic=True)
    assert c.metadata["is_synthetic"] is True
    assert c.metadata["source"].startswith("Synthetic_")
    assert c.metadata["seed"] == 42
    assert "adjustments" in c.metadata


def test_periodic_network_has_correct_spectral_radius():
    from puremacro.trade.regularize import compute_spectral_radius
    rho, lo, hi = compute_spectral_radius(np.array([[0., 2.], [.2, 0.]]), max_iter=60, tol=1e-6)
    assert abs(rho - np.sqrt(.4)) < 1e-6
    assert lo <= np.sqrt(.4) <= hi
    assert hi < 1


@pytest.mark.parametrize("function", ["verify_theorems_1_to_4", "decompose_hicksian_ev_3way"])
def test_unsupported_welfare_certificates_are_explicitly_unavailable(calibration, function):
    from puremacro.trade import policy_analytics
    kwargs = {"eq_result": None} if function.startswith("decompose") else {}
    with pytest.raises(NotImplementedError, match="unavailable"):
        getattr(policy_analytics, function)(calibration, **kwargs)


def test_cp_offsetting_costs_preserve_tariff_revenue():
    from puremacro.trade.caliendo_parro import CaliendoParroModel
    cp = CaliendoParroModel(trade_shares=np.array([[[.8,.2],[.2,.8]]]),
        gamma_va=np.full((2,1),.5), gamma_io=np.full((2,1,1),.5), alpha=np.ones((2,1)),
        theta=np.array([4.]), labor_income=np.array([100.,100.]))
    tariffs = np.array([[[1.,1.2],[1.2,1.]]])
    result = cp.solve_counterfactual(tariffs_new=tariffs, d_hat=1/tariffs)
    assert result.converged and result.iterations > 0
    _, _, expected = cp._solve_expenditures(result.w_hat, result.pi_prime, tariffs, np.zeros(2))
    np.testing.assert_allclose(result.tariff_revenue_prime, expected, rtol=1e-8)
    assert np.all(result.tariff_revenue_prime > 0)


def test_tiny_relaxation_does_not_certify_nash(calibration):
    from puremacro.trade.optimal_tariffs import solve_multilateral_nash_tariffs
    result = solve_multilateral_nash_tariffs(calibration, player_countries=calibration.country_codes,
        metric="equivalent_variation", relaxation=1e-8, max_iter=2, tol=1e-4)
    assert not result.converged
    assert result.metadata["max_regret"] > 1
    assert result.outer_error > 1e-4


def test_failed_markov_switching_has_no_equilibrium_moments():
    from puremacro.dsge.markov_switching import solve_ms_dsge
    result = solve_ms_dsge(A=[np.array([[1.]])], B=[np.array([[-3.]])],
        C=[np.array([[2.5]])], D=[np.array([[1.]])], transition_matrix=np.ones((1,1)), max_iter=10)
    assert not result.converged and not result.mean_square_stable
    assert np.isnan(result.spectral_radius_mss)
    assert np.isnan(np.asarray(result.ergodic_cov)).all()
    t = result.T[0][0,0]
    assert abs(result.diff - abs(t*t - 3*t + 2.5)) < 1e-10


def test_training_step_gradient_uses_current_state(monkeypatch):
    from puremacro.vfi.deep_macro import DeepMacroMLP, DeepMacroModel, solve_deep_macro
    forward, backward = DeepMacroMLP.forward, DeepMacroMLP.backward
    current_input = []
    checked = []

    def record(self, x):
        if np.asarray(x).shape[0] == 4 and not current_input:
            current_input.append(np.array(x, copy=True))
        return forward(self, x)

    def check(self, upstream):
        actual = backward(self, upstream)
        # Check a full training-step VJP by finite differences with the Euler
        # target detached. Neither next-state activations nor target derivatives
        # belong in this gradient.
        h = 1e-6
        for array, gradient in zip(
            [a for pair in zip(self.weights, self.biases) for a in pair],
            [a for pair in actual for a in pair],
        ):
            numerical = np.zeros_like(array)
            for idx in np.ndindex(array.shape):
                original = array[idx]
                array[idx] = original + h
                plus = np.sum(forward(self, current_input[0]) * upstream)
                array[idx] = original - h
                minus = np.sum(forward(self, current_input[0]) * upstream)
                array[idx] = original
                numerical[idx] = (plus - minus) / (2*h)
            np.testing.assert_allclose(gradient, numerical, rtol=1e-6, atol=1e-10)
        checked.append(True)
        return actual

    monkeypatch.setattr(DeepMacroMLP, "forward", record)
    monkeypatch.setattr(DeepMacroMLP, "backward", check)
    solve_deep_macro(DeepMacroModel(n_states=1, n_controls=1), hidden_dims=(4,),
        n_epochs=1, trajectory_length=10, burn_in=2, batch_size=4)
    assert checked == [True]


@pytest.mark.parametrize("closure", ["lump_sum", "deficit_reduction"])
def test_reported_tariff_revenue_reconciles_fiscal_budget(calibration, closure):
    c = calibration
    tau = np.ones((4,2,2)); tau[2:, :, 0] = [[1.05, 1.15], [1.2, 1.3]]
    result = solve_trade_equilibrium(c, tau=tau, fiscal_closure=closure, tariff_revenue_mode="schedule", sigma=2, tol=1e-8, max_iter=150)
    assert result.converged
    # The calibration's generated final-demand tax is zero.
    taxes = np.sum(c.tax * result.y_sol, axis=1).ravel()
    np.testing.assert_allclose(result.T_sol.ravel(), taxes + result.tariffs, atol=1e-7)


def test_parity_aligns_state_and_shock_columns():
    dr = canonical_growth_2nd_order().decision_rules()
    shuffled = replace(dr, **{name: getattr(dr, name).iloc[::-1, ::-1]
                              for name in ("ghx", "ghu", "ghxx", "ghxu", "ghuu")})
    assert verify_dynare_parity(dr, shuffled, order=2).passed


def test_labeled_mrio_file_units_provenance_and_accounting():
    import hashlib
    from pathlib import Path
    from puremacro.trade.data import load_figaro
    path = Path(__file__).parent / "fixtures/trade/figaro_harmonized_small.csv"
    result = load_figaro(file_path=path, eur_to_usd=2., regularize=False)
    assert tuple(result.country_codes) == ("AAA", "BBB")
    np.testing.assert_allclose(result.ytot, 14.)
    assert result.metadata["is_synthetic"] is False
    assert result.metadata["sha256"] == hashlib.sha256(path.read_bytes()).hexdigest()
    assert result.metadata["exchange_rate_usd_per_eur"] == 2.
    assert all(v["changed_entries"] == 0 for v in result.metadata["adjustments"].values())


def test_labeled_mrio_file_rejects_reordered_rows(tmp_path):
    from pathlib import Path
    import pandas as pd
    from puremacro.trade.data import load_figaro
    frame = pd.read_csv(Path(__file__).parent / "fixtures/trade/figaro_harmonized_small.csv", index_col=0)
    path = tmp_path / "misordered.csv"
    frame.iloc[[1,0,2,3,4,5]].to_csv(path)
    with pytest.raises(ValueError, match="country-major"):
        load_figaro(file_path=path)


def test_dynare_state_column_order_uses_parameter_specific_dr_indices():
    from puremacro.dsge.dynare_results import load_dynare_dr
    raw = {"oo_": {"dr": {
        "ghx": np.array([[11., 12.], [21., 22.], [31., 32.]]),
        "ghu": np.array([[1., 2.], [3., 4.], [5., 6.]]),
        "ys": np.array([100., 200., 300.]),
        "order_var": np.array([3, 1, 2]), "state_var": np.array([3, 1]),
    }}, "M_": {"endo_names": ["x", "y", "z"], "exo_names": ["e", "v"],
                "state_var": {"declaration_order": np.array([1, 3])}}}
    dr = load_dynare_dr(raw)
    assert dr.state_variables == ("z", "x")
    np.testing.assert_array_equal(dr.ghx.loc["x"], [21., 22.])
    assert dr.ys.loc["x"] == 100.


def test_policy_search_rejects_failed_inner_equilibrium(monkeypatch, calibration):
    from puremacro.trade import optimal_tariffs
    result = solve_trade_equilibrium(calibration, method="condensed")
    failed = replace(result, converged=False)
    monkeypatch.setattr(optimal_tariffs, "solve_trade_equilibrium", lambda *a, **k: failed)
    with pytest.raises(RuntimeError, match="did not converge"):
        optimal_tariffs.compute_unilateral_optimal_tariff(calibration, country_idx=0)


def test_unilateral_policy_uses_schedule_accounting(calibration):
    from puremacro.trade.optimal_tariffs import compute_unilateral_optimal_tariff
    result = compute_unilateral_optimal_tariff(calibration, country_idx=0,
        metric="consumption", tariff_max=.2, num_grid=3, method="grid")
    assert result.equilibrium.metadata["tariff_revenue_mode"] == "schedule"
    assert result.equilibrium.max_residual <= result.metadata["ge_tol"]


def test_malformed_dynare_risk_vector_is_not_resized_into_a_match():
    dr = canonical_growth_2nd_order().decision_rules()
    fields = {name: getattr(dr, name).to_numpy() for name in
              ("ys", "ghx", "ghu", "ghxx", "ghxu", "ghuu", "ghs2")}
    fields["ghs2"] = np.array([0.])
    raw = {"oo_": {"dr": fields}, "M_": {
        "endo_names": list(dr.variable_names), "exo_names": list(dr.shock_names),
        "state_var": [list(dr.variable_names).index(v)+1 for v in dr.state_variables]}}
    result = verify_dynare_parity(dr, raw, order=2)
    assert not result.passed and result.details["status"] == "UNAVAILABLE"
    assert "ghs2" in result.details["error"]
