"""``LinearModel.smoother`` and ``.forecast`` — Dynare's ``calib_smoother``.

Because the filter state is ``[x_t; u_t]``, the smoothed structural shocks are
literally the last ``n_e`` rows of the smoothed state: no separate disturbance
smoother is involved. The first test below is the one that matters — with one
observable, one shock, no measurement error and a known initial state, the map
from observables to shocks is bijective, so a correct smoother must invert it.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from puremacro.dsge import load_mod
from puremacro.dsge.decomposition import _extract_companion_matrices


_RBC = """
var c k a;
varexo eps;
parameters alpha beta delta gamma rho;
alpha = 0.30; beta = 0.99; delta = 0.025; gamma = 1.0; rho = 0.80;
model;
  c^(-gamma) = beta * c(+1)^(-gamma) * (alpha * exp(a(+1)) * k^(alpha - 1.0) + 1.0 - delta);
  k = exp(a) * k(-1)^alpha - c + (1.0 - delta) * k(-1);
  a = rho * a(-1) + eps;
end;
initval; k = 38.0; a = 0.0; c = 2.0; end;
shocks; var eps; stderr 0.01; end;
varobs c;
"""


@pytest.fixture(scope="module")
def rbc():
    return load_mod(_RBC)


def _simulate(model, u, obs):
    """Observable path generated by the model's own companion recursion."""
    A, B, C, D, ys, variables, shocks, states, _ = _extract_companion_matrices(model)
    rows = [variables.index(v) for v in obs]
    y = np.zeros((len(u), len(obs)))
    x = np.zeros(len(states))
    for t in range(len(u)):
        y[t] = (ys + C @ x + D @ u[t])[rows]
        x = A @ x + B @ u[t]
    return pd.DataFrame(y, columns=list(obs))


def test_smoother_recovers_the_simulated_shocks(rbc):
    """One observable, one shock, no measurement error, known x_0."""
    rng = np.random.default_rng(3)
    u_true = rng.standard_normal((200, 1)) * 0.01
    data = _simulate(rbc, u_true, ["c"])

    m = rbc.n_states + len(rbc.shocks)
    res = rbc.smoother(data, a0=np.zeros(m), P0=1e-10 * np.eye(m))
    np.testing.assert_allclose(
        res.shocks["eps"].to_numpy()[10:], u_true[10:, 0], rtol=0, atol=1e-6)


def test_smoothed_observables_reproduce_the_data(rbc):
    """With no measurement error the fitted observables are the data."""
    rng = np.random.default_rng(5)
    data = _simulate(rbc, rng.standard_normal((120, 1)) * 0.01, ["c"])
    res = rbc.smoother(data)
    np.testing.assert_allclose(
        res.smoothed_obs["c"].to_numpy(), data["c"].to_numpy(), rtol=0, atol=1e-8)


def test_smoother_output_shapes_and_labels(rbc):
    rng = np.random.default_rng(7)
    data = _simulate(rbc, rng.standard_normal((60, 1)) * 0.01, ["c"])
    res = rbc.smoother(data)
    assert list(res.shocks.columns) == list(rbc.shocks)
    assert list(res.states.columns) == list(rbc.states)
    assert list(res.smoothed_obs.columns) == ["c"]
    assert len(res.shocks) == len(res.states) == len(res.smoothed_obs) == 60
    assert np.isfinite(res.loglik)
    assert res.varobs == ("c",)


def test_smoother_defaults_to_the_mod_files_varobs(rbc):
    """The .mod file says `varobs c;` — the caller should not repeat it."""
    rng = np.random.default_rng(9)
    data = _simulate(rbc, rng.standard_normal((40, 1)) * 0.01, ["c"])
    assert rbc.smoother(data).varobs == ("c",)


def test_smoother_rejects_data_missing_an_observable(rbc):
    with pytest.raises(ValueError, match="c"):
        rbc.smoother(pd.DataFrame({"wrong": np.zeros(20)}))


def test_smoother_presentation_contract(rbc):
    rng = np.random.default_rng(11)
    data = _simulate(rbc, rng.standard_normal((40, 1)) * 0.01, ["c"])
    res = rbc.smoother(data)
    assert isinstance(res.summary(), str) and res.summary()
    for fn in (res.to_markdown, res.to_latex, res.to_typst):
        assert isinstance(fn(), str) and fn()


def test_observation_trends_round_trip(rbc):
    """A declared trend is removed before filtering and put back afterwards,
    so the fitted observables still reproduce the trended data."""
    rng = np.random.default_rng(13)
    data = _simulate(rbc, rng.standard_normal((80, 1)) * 0.01, ["c"])
    trended = data.copy()
    trended["c"] = trended["c"] + 0.002 * np.arange(len(trended))
    res = rbc.smoother(trended, observation_trends={"c": 0.002})
    np.testing.assert_allclose(
        res.smoothed_obs["c"].to_numpy(), trended["c"].to_numpy(), rtol=0, atol=1e-8)


def test_forecast_mean_converges_to_the_steady_state(rbc):
    rng = np.random.default_rng(17)
    data = _simulate(rbc, rng.standard_normal((100, 1)) * 0.01, ["c"])
    res = rbc.forecast(horizon=500, data=data)
    np.testing.assert_allclose(
        res.mean.iloc[-1].to_numpy(),
        rbc.steady_state[list(res.mean.columns)].to_numpy(), rtol=1e-4)


def test_forecast_bands_widen_monotonically(rbc):
    rng = np.random.default_rng(19)
    data = _simulate(rbc, rng.standard_normal((100, 1)) * 0.01, ["c"])
    res = rbc.forecast(horizon=20, data=data, ci=0.90)
    width = (res.upper["c"] - res.lower["c"]).to_numpy()
    assert np.all(np.diff(width) >= -1e-12), width
    assert np.all(res.lower["c"] < res.mean["c"]) and np.all(res.mean["c"] < res.upper["c"])


def test_forecast_band_width_matches_the_requested_level(rbc):
    """The band is mean +/- z_{(1+ci)/2} * sd, not a fixed two sigma."""
    from scipy.stats import norm

    rng = np.random.default_rng(23)
    data = _simulate(rbc, rng.standard_normal((100, 1)) * 0.01, ["c"])
    r90 = rbc.forecast(horizon=5, data=data, ci=0.90)
    r68 = rbc.forecast(horizon=5, data=data, ci=0.68)
    ratio = ((r90.upper["c"] - r90.mean["c"]) / (r68.upper["c"] - r68.mean["c"])).to_numpy()
    np.testing.assert_allclose(ratio, norm.ppf(0.95) / norm.ppf(0.84), rtol=1e-6)


def test_forecast_presentation_contract(rbc):
    rng = np.random.default_rng(29)
    data = _simulate(rbc, rng.standard_normal((40, 1)) * 0.01, ["c"])
    res = rbc.forecast(horizon=8, data=data)
    assert isinstance(res.summary(), str) and res.summary()
    for fn in (res.to_markdown, res.to_latex, res.to_typst):
        assert isinstance(fn(), str) and fn()


def test_smoothed_shocks_agree_with_the_shock_decomposition_path(rbc):
    """SmootherResult.shock_decomposition() delegates to the existing tested
    entry point. The two arrive at the smoothed shocks by different routes, so
    this pins that they agree rather than assuming it."""
    rng = np.random.default_rng(31)
    data = _simulate(rbc, rng.standard_normal((80, 1)) * 0.01, ["c"])
    res = rbc.smoother(data)
    dec = res.shock_decomposition()
    np.testing.assert_allclose(
        dec.smoothed_shocks["eps"].to_numpy(), res.shocks["eps"].to_numpy(),
        rtol=0, atol=1e-8)
