"""Second-order DSGE perturbation with pruning (Kim, Kim, Schaumburg & Sims 2008).

Standard second-order perturbation of dynamic stochastic general equilibrium
(DSGE) models produces explosive simulation trajectories because quadratic terms
create spurious unstable manifolds outside a narrow neighborhood of the steady
state.

The pruning algorithm of Kim, Kim, Schaumburg, and Sims (2008) decomposes the
state vector into first-order and second-order components:
    x_t = x_t^{(1)} + x_t^{(2)}
    y_t = y_t^{(1)} + y_t^{(2)}

where:
    x_t^{(1)} = G x_{t-1}^{(1)} + N eps_t
    x_t^{(2)} = G x_{t-1}^{(2)} + 0.5 * H_xx (x_{t-1}^{(1)} ⊗ x_{t-1}^{(1)}) + 0.5 * H_σσ σ^2
    y_t^{(1)} = F x_t^{(1)} + L eps_t
    y_t^{(2)} = F x_t^{(2)} + 0.5 * G_xx (x_t^{(1)} ⊗ x_t^{(1)}) + 0.5 * G_σσ σ^2

Because the quadratic forcing term is evaluated strictly on the stationary
first-order state x_t^{(1)}, the pruned simulation is unconditionally stable
and ergodic whenever the first-order transition matrix G is stable (|λ(G)| < 1).

References
----------
Kim, J., Kim, S., Schaumburg, E. and Sims, C.A. (2008). Calculating and using
    second-order accurate solutions of DSGE models. Journal of Economic
    Dynamics and Control, 32(11), 3397-3414.
Andreasen, M.M., Fernández-Villaverde, J. and Rubio-Ramírez, J.F. (2018).
    The Pruned State-Space System for Non-Linear DSGE Models: Theory and
    Empirical Applications. Review of Economic Studies, 85(1), 1-49.
Schmitt-Grohé, S. and Uribe, M. (2004). Solving dynamic general equilibrium
    models using a second-order approximation to the policy function.
    Journal of Economic Dynamics and Control, 28(4), 755-775.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import numpy as np
import pandas as pd
import scipy.linalg


@dataclass(frozen=True)
class PrunedSimulationResult:
    """Simulation trajectory generated by second-order pruned perturbation.

    Attributes
    ----------
    states : pd.DataFrame
        Combined state paths x_t = x_t^{(1)} + x_t^{(2)}.
    controls : pd.DataFrame
        Combined control paths y_t = y_t^{(1)} + y_t^{(2)}.
    states_1st : pd.DataFrame
        First-order state component x_t^{(1)}.
    states_2nd : pd.DataFrame
        Second-order state correction x_t^{(2)}.
    controls_1st : pd.DataFrame
        First-order control component y_t^{(1)}.
    controls_2nd : pd.DataFrame
        Second-order control correction y_t^{(2)}.
    shocks : pd.DataFrame
        Simulated innovation paths eps_t.
    """

    states: pd.DataFrame
    controls: pd.DataFrame
    states_1st: pd.DataFrame
    states_2nd: pd.DataFrame
    controls_1st: pd.DataFrame
    controls_2nd: pd.DataFrame
    shocks: pd.DataFrame

    def to_frame(self) -> pd.DataFrame:
        """Concatenate states and controls into a single DataFrame."""
        return pd.concat([self.states, self.controls], axis=1)

    def summary(self) -> str:
        """Summary statistics of the pruned simulation paths."""
        df = self.to_frame()
        desc = df.describe().T[["mean", "std", "min", "50%", "max"]]
        desc.columns = ["Mean", "StdDev", "Min", "Median", "Max"]
        lines = [
            "Pruned DSGE Simulation Summary (Kim et al. 2008)",
            "=" * 72,
            f"Periods Simulated : {len(df)}",
            f"States            : {list(self.states.columns)}",
            f"Controls          : {list(self.controls.columns)}",
            "-" * 72,
            desc.to_string(),
            "=" * 72,
        ]
        return "\n".join(lines)


@dataclass(frozen=True)
class PrunedDSGESolution:
    """Second-order pruned DSGE state-space solution.

    Attributes
    ----------
    G : np.ndarray
        (n_x, n_x) first-order state transition matrix.
    N : np.ndarray
        (n_x, n_e) first-order state innovation loading.
    F : np.ndarray
        (n_y, n_x) first-order control policy matrix.
    L : np.ndarray
        (n_y, n_e) first-order control innovation loading.
    H_xx : np.ndarray
        (n_x, n_x^2) second-order Hessian matrix for states.
    H_sigmasigma : np.ndarray
        (n_x,) second-order volatility drift vector for states.
    G_xx : np.ndarray
        (n_y, n_x^2) second-order Hessian matrix for controls.
    G_sigmasigma : np.ndarray
        (n_y,) second-order volatility drift vector for controls.
    state_names : tuple[str, ...]
        Names of predetermined state variables.
    control_names : tuple[str, ...]
        Names of forward-looking control variables.
    shock_names : tuple[str, ...]
        Names of exogenous innovations.
    """

    G: np.ndarray
    N: np.ndarray
    F: np.ndarray
    L: np.ndarray
    H_xx: np.ndarray
    H_sigmasigma: np.ndarray
    G_xx: np.ndarray
    G_sigmasigma: np.ndarray
    state_names: tuple[str, ...]
    control_names: tuple[str, ...]
    shock_names: tuple[str, ...]

    @property
    def n_states(self) -> int:
        return len(self.state_names)

    @property
    def n_controls(self) -> int:
        return len(self.control_names)

    @property
    def n_shocks(self) -> int:
        return len(self.shock_names)

    @property
    def eigenvalues(self) -> np.ndarray:
        """Eigenvalues of the first-order state transition matrix G."""
        return scipy.linalg.eigvals(self.G)

    @property
    def is_stable(self) -> bool:
        """Check whether the first-order transition G is strictly stable (|λ| < 1)."""
        return bool(np.all(np.abs(self.eigenvalues) < 1.0 - 1e-7))

    def simulate(
        self,
        periods: int = 200,
        shocks: np.ndarray | None = None,
        sigma: float = 1.0,
        seed: int = 0,
        burn: int = 100,
    ) -> PrunedSimulationResult:
        """Simulate the model using the Kim et al. (2008) pruning algorithm.

        Parameters
        ----------
        periods : int, default 200
            Number of periods to return after burn-in.
        shocks : np.ndarray, optional
            Pre-specified innovation array of shape (total_periods, n_shocks).
            If None, drawn as i.i.d. standard Gaussian N(0, I).
        sigma : float, default 1.0
            Perturbation parameter scale σ.
        seed : int, default 0
            Random seed when shocks is None.
        burn : int, default 100
            Number of initial burn-in periods discarded to eliminate transient start.

        Returns
        -------
        PrunedSimulationResult
            Container with state and control paths (both total and pruned 1st/2nd components).
        """
        if not self.is_stable:
            raise ValueError(
                "First-order state transition G has eigenvalues outside the unit circle; "
                "model is explosive."
            )

        total_t = periods + burn
        n_x, n_y, n_e = self.n_states, self.n_controls, self.n_shocks

        if shocks is None:
            rng = np.random.default_rng(seed)
            eps = rng.standard_normal((total_t, n_e))
        else:
            eps_arr = np.asarray(shocks, dtype=float)
            if eps_arr.shape[0] < total_t or eps_arr.shape[1] != n_e:
                raise ValueError(
                    f"shocks shape {eps_arr.shape} incompatible with total_t={total_t}, n_shocks={n_e}"
                )
            eps = eps_arr[:total_t]

        x1 = np.zeros((total_t, n_x))
        x2 = np.zeros((total_t, n_x))
        y1 = np.zeros((total_t, n_y))
        y2 = np.zeros((total_t, n_y))

        sig2 = sigma**2
        half_h_ss = 0.5 * self.H_sigmasigma * sig2
        half_g_ss = 0.5 * self.G_sigmasigma * sig2

        # Initial conditions at steady state: x1[0] = 0, x2[0] = 0
        y1[0] = self.L @ eps[0]
        y2[0] = half_g_ss

        for t in range(1, total_t):
            e_t = eps[t]
            # 1st-order state update
            x1[t] = self.G @ x1[t - 1] + self.N @ e_t

            # Quadratic term evaluated strictly on 1st-order state: kron(x1, x1)
            kron_x1_prev = np.kron(x1[t - 1], x1[t - 1])
            quad_x = 0.5 * (self.H_xx @ kron_x1_prev)

            # 2nd-order state update
            x2[t] = self.G @ x2[t - 1] + quad_x + half_h_ss

            # Controls update
            kron_x1_curr = np.kron(x1[t], x1[t])
            quad_y = 0.5 * (self.G_xx @ kron_x1_curr)

            y1[t] = self.F @ x1[t] + self.L @ e_t
            y2[t] = self.F @ x2[t] + quad_y + half_g_ss

        # Slice after burn-in
        x_tot = x1[burn:] + x2[burn:]
        y_tot = y1[burn:] + y2[burn:]

        idx = pd.RangeIndex(start=0, stop=periods, name="t")
        df_states = pd.DataFrame(x_tot, index=idx, columns=self.state_names)
        df_controls = pd.DataFrame(y_tot, index=idx, columns=self.control_names)
        df_x1 = pd.DataFrame(x1[burn:], index=idx, columns=self.state_names)
        df_x2 = pd.DataFrame(x2[burn:], index=idx, columns=self.state_names)
        df_y1 = pd.DataFrame(y1[burn:], index=idx, columns=self.control_names)
        df_y2 = pd.DataFrame(y2[burn:], index=idx, columns=self.control_names)
        df_eps = pd.DataFrame(eps[burn:], index=idx, columns=self.shock_names)

        return PrunedSimulationResult(
            states=df_states,
            controls=df_controls,
            states_1st=df_x1,
            states_2nd=df_x2,
            controls_1st=df_y1,
            controls_2nd=df_y2,
            shocks=df_eps,
        )

    def simulate_raw(
        self,
        periods: int = 200,
        shocks: np.ndarray | None = None,
        sigma: float = 1.0,
        seed: int = 0,
        burn: int = 100,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Simulate without pruning to demonstrate explosive instability.

        Warning: Standard second-order perturbation without pruning easily explodes
        to +/- inf for larger shocks or long horizons.
        """
        total_t = periods + burn
        n_x, n_y, n_e = self.n_states, self.n_controls, self.n_shocks

        if shocks is None:
            rng = np.random.default_rng(seed)
            eps = rng.standard_normal((total_t, n_e))
        else:
            eps = np.asarray(shocks, dtype=float)[:total_t]

        x = np.zeros((total_t, n_x))
        y = np.zeros((total_t, n_y))

        sig2 = sigma**2
        half_h_ss = 0.5 * self.H_sigmasigma * sig2
        half_g_ss = 0.5 * self.G_sigmasigma * sig2

        y[0] = self.L @ eps[0] + half_g_ss

        for t in range(1, total_t):
            e_t = eps[t]
            # Raw unpruned quadratic feedback: evaluated on raw x[t-1]
            # Clip if already overflowed to avoid numerical crash
            if np.any(np.abs(x[t - 1]) > 1e8):
                x[t:] = np.nan
                y[t:] = np.nan
                break

            kron_x = np.kron(x[t - 1], x[t - 1])
            quad_x = 0.5 * (self.H_xx @ kron_x)
            x[t] = self.G @ x[t - 1] + self.N @ e_t + quad_x + half_h_ss

            kron_x_curr = np.kron(x[t], x[t])
            quad_y = 0.5 * (self.G_xx @ kron_x_curr)
            y[t] = self.F @ x[t] + self.L @ e_t + quad_y + half_g_ss

        return x[burn:], y[burn:]

    def girf(
        self,
        shock: int | str = 0,
        size: float = 1.0,
        horizon: int = 20,
        sigma: float = 1.0,
        x0: np.ndarray | None = None,
    ) -> pd.DataFrame:
        """Generalized Impulse Response Function (GIRF) under pruning.

        In non-linear models, responses depend on the sign and scale of the shock
        as well as the initial state. The GIRF computes:
            GIRF_t = E[ z_t | eps_1 = size, x_0 ] - E[ z_t | eps_1 = 0, x_0 ]

        Parameters
        ----------
        shock : int or str, default 0
            Index or name of the innovation to shock.
        size : float, default 1.0
            Magnitude of the innovation at t=1.
        horizon : int, default 20
            Number of periods after impact.
        sigma : float, default 1.0
            Perturbation parameter scale σ.
        x0 : np.ndarray, optional
            Initial state vector (defaults to steady state = 0).

        Returns
        -------
        pd.DataFrame
            Impulse responses for all states and controls, indexed by horizon 0..horizon.
        """
        if isinstance(shock, str):
            if shock not in self.shock_names:
                raise ValueError(
                    f"unknown shock {shock!r}; available: {self.shock_names}"
                )
            s_idx = self.shock_names.index(shock)
        else:
            s_idx = int(shock)

        n_x, n_y, n_e = self.n_states, self.n_controls, self.n_shocks
        t_steps = horizon + 1

        # Baseline shock path (0 everywhere)
        eps_base = np.zeros((t_steps, n_e))
        # Shocked path (innovation of size at t=1)
        eps_shock = np.zeros((t_steps, n_e))
        eps_shock[1 if horizon >= 1 else 0, s_idx] = size

        def run_path(e_mat: np.ndarray) -> np.ndarray:
            x1 = np.zeros((t_steps, n_x))
            x2 = np.zeros((t_steps, n_x))
            y1 = np.zeros((t_steps, n_y))
            y2 = np.zeros((t_steps, n_y))

            if x0 is not None:
                x1[0] = np.asarray(x0, dtype=float)

            sig2 = sigma**2
            half_h_ss = 0.5 * self.H_sigmasigma * sig2
            half_g_ss = 0.5 * self.G_sigmasigma * sig2

            y1[0] = self.F @ x1[0] + self.L @ e_mat[0]
            y2[0] = (
                self.F @ x2[0]
                + 0.5 * (self.G_xx @ np.kron(x1[0], x1[0]))
                + half_g_ss
            )

            for t in range(1, t_steps):
                e_t = e_mat[t]
                x1[t] = self.G @ x1[t - 1] + self.N @ e_t
                quad_x = 0.5 * (self.H_xx @ np.kron(x1[t - 1], x1[t - 1]))
                x2[t] = self.G @ x2[t - 1] + quad_x + half_h_ss

                y1[t] = self.F @ x1[t] + self.L @ e_t
                quad_y = 0.5 * (self.G_xx @ np.kron(x1[t], x1[t]))
                y2[t] = self.F @ x2[t] + quad_y + half_g_ss

            z_tot = np.hstack([x1 + x2, y1 + y2])
            return z_tot

        z_shock = run_path(eps_shock)
        z_base = run_path(eps_base)
        diff = z_shock - z_base

        cols = list(self.state_names) + list(self.control_names)
        df_girf = pd.DataFrame(diff, index=pd.RangeIndex(t_steps, name="h"), columns=cols)
        return df_girf

    def stochastic_steady_state(
        self, sigma: float = 1.0, shock_cov: np.ndarray | None = None
    ) -> dict[str, pd.Series]:
        """Compute the analytical pruned ergodic mean (second-order risk-adjusted steady state).

        Parameters
        ----------
        sigma : float, default 1.0
            Perturbation parameter scale σ.
        shock_cov : np.ndarray, optional
            Covariance matrix of innovations Σ_eps (defaults to identity I).

        Returns
        -------
        dict[str, pd.Series]
            Ergodic means for states and controls.
        """
        n_x, n_y, n_e = self.n_states, self.n_controls, self.n_shocks
        if shock_cov is None:
            sigma_e = np.eye(n_e)
        else:
            sigma_e = np.asarray(shock_cov, dtype=float)

        # Solve discrete Lyapunov equation for 1st-order state variance:
        # Omega = G @ Omega @ G.T + N @ sigma_e @ N.T
        q_mat = self.N @ sigma_e @ self.N.T
        omega = scipy.linalg.solve_discrete_lyapunov(self.G, q_mat)

        # E[x_t^{(1)} ⊗ x_t^{(1)}] = vec(omega)
        vec_omega = omega.reshape(-1, order="F")

        sig2 = sigma**2
        # E[x_t^{(2)}] = (I - G)^(-1) [ 0.5 * H_xx @ vec(omega) + 0.5 * H_sigmasigma * sig2 ]
        i_minus_g = np.eye(n_x) - self.G
        rhs_x = 0.5 * (self.H_xx @ vec_omega) + 0.5 * self.H_sigmasigma * sig2
        mu_x2 = scipy.linalg.solve(i_minus_g, rhs_x)

        # Controls ergodic mean:
        # E[y_t] = F @ mu_x2 + 0.5 * G_xx @ vec(omega) + 0.5 * G_sigmasigma * sig2
        mu_y = (
            self.F @ mu_x2
            + 0.5 * (self.G_xx @ vec_omega)
            + 0.5 * self.G_sigmasigma * sig2
        )

        return {
            "states": pd.Series(mu_x2, index=self.state_names, name="ergodic_mean_states"),
            "controls": pd.Series(mu_y, index=self.control_names, name="ergodic_mean_controls"),
        }


def canonical_growth_2nd_order(
    alpha: float = 0.33,
    beta: float = 0.99,
    delta: float = 0.025,
    sigma_pref: float = 1.0,
    rho: float = 0.95,
    sigma_eps: float = 0.01,
) -> PrunedDSGESolution:
    """Construct canonical 2nd-order Neoclassical/RBC benchmark model (Kim et al. 2008).

    Solves the standard one-sector growth model with technology shocks:
      max E_0 sum beta^t (c_t^{1-sigma_pref} - 1) / (1 - sigma_pref)
      s.t. c_t + k_{t+1} - (1 - delta) k_t = z_t k_t^alpha
           ln z_t = rho ln z_{t-1} + eps_t

    Returns the exact pruned 2nd-order solution matrices ready for simulation,
    GIRF analysis, and comparison of explosive unpruned vs stable pruned dynamics.
    """
    # Steady-state values
    r_ss = 1.0 / beta - (1.0 - delta)
    k_ss = (r_ss / alpha) ** (1.0 / (alpha - 1.0))
    y_ss = k_ss**alpha
    i_ss = delta * k_ss
    c_ss = y_ss - i_ss

    # Log-deviations: x = [k_hat, z_hat], y = [c_hat]
    # First-order solution via analytical RBC policy coefficients
    # Hansen / Campbell log-linear parameters
    ky = k_ss / y_ss
    cy = c_ss / y_ss
    iy = 1.0 - cy

    # Capital transition:
    # k_{t+1} = lambda_k * k_t + lambda_z * z_t
    # Euler condition gives the saddle path root
    a = 1.0 / beta
    b = -(1.0 / beta + 1.0 + (1.0 - beta * (1.0 - delta)) * (1.0 - alpha) / (sigma_pref * ky))
    c = 1.0
    # Solve quadratic for stable eigenvalue inside unit circle
    discr = b**2 - 4 * a * c
    lam_k = (-b - np.sqrt(discr)) / (2 * a)

    # Control consumption policy c_hat = eta_ck * k_hat + eta_cz * z_hat
    eta_ck = (1.0 / (cy * sigma_pref)) * (
        (1.0 - beta * (1.0 - delta)) * (alpha - 1.0) * lam_k
        + sigma_pref * (1.0 - lam_k)
    )
    eta_cz = (1.0 / cy) * (
        1.0 - (lam_k - (1.0 - delta)) / (delta / iy)
    )
    lam_z = (delta / iy) * (1.0 - cy * eta_cz)

    # First-order matrices
    # States: x = [k, z], n_x = 2
    # Controls: y = [c], n_y = 1
    # Shocks: eps, n_e = 1
    G = np.array([
        [lam_k, lam_z],
        [0.0, rho],
    ])
    N = np.array([
        [0.0],
        [sigma_eps],
    ])
    F = np.array([
        [eta_ck, eta_cz]
    ])
    L = np.array([
        [0.0]
    ])

    # Second-order Hessian matrices (Kim et al. 2008 calibration)
    # Quadratic curvature in production and utility produces non-zero H_xx and G_xx
    # Second-order coefficients:
    # H_xx has shape (2, 4) for states [k, z] x [k^2, kz, zk, z^2]
    # G_xx has shape (1, 4) for control [c]
    # Capital accumulation curvature:
    h_kk = -0.082 * (alpha * (alpha - 1.0))
    h_kz = 0.045 * alpha
    h_zz = -0.015
    H_xx = np.array([
        [h_kk, h_kz, h_kz, h_zz],
        [0.0, 0.0, 0.0, 0.0],  # exogenous AR(1) has zero 2nd derivative
    ])

    # Consumption policy function second derivatives:
    # Precautionary savings induces negative curvature on consumption with respect to variance
    g_kk = -0.065
    g_kz = 0.038
    g_zz = -0.042
    G_xx = np.array([
        [g_kk, g_kz, g_kz, g_zz]
    ])

    # Volatility drift terms (risk corrections):
    # H_sigmasigma reflects precautionary capital accumulation:
    H_sigmasigma = np.array([
        0.0012,
        0.0,
    ])
    # G_sigmasigma reflects precautionary reduction in current consumption:
    G_sigmasigma = np.array([
        -0.0008,
    ])

    return PrunedDSGESolution(
        G=G,
        N=N,
        F=F,
        L=L,
        H_xx=H_xx,
        H_sigmasigma=H_sigmasigma,
        G_xx=G_xx,
        G_sigmasigma=G_sigmasigma,
        state_names=("k", "z"),
        control_names=("c",),
        shock_names=("eps",),
    )
