"""Second-order DSGE perturbation with pruning (Kim, Kim, Schaumburg & Sims 2008).

Standard second-order perturbation of dynamic stochastic general equilibrium
(DSGE) models produces explosive simulation trajectories because quadratic terms
create spurious unstable manifolds outside a narrow neighborhood of the steady
state.

The pruning algorithm of Kim, Kim, Schaumburg, and Sims (2008) decomposes the
state vector into first-order and second-order components. In Dynare's timing
(``x_t`` is the state at the end of period ``t`` and responds to ``u_t``):

    x_t^{(1)} = G x_{t-1}^{(1)} + N u_t
    x_t^{(2)} = G x_{t-1}^{(2)} + 0.5 H_xx (x_{t-1}^{(1)} ⊗ x_{t-1}^{(1)})
                + H_xu (x_{t-1}^{(1)} ⊗ u_t) + 0.5 H_uu (u_t ⊗ u_t) + 0.5 H_σσ σ²
    y_t^{(1)} = F x_{t-1}^{(1)} + L u_t
    y_t^{(2)} = F x_{t-1}^{(2)} + 0.5 G_xx (x_{t-1}^{(1)} ⊗ x_{t-1}^{(1)})
                + G_xu (x_{t-1}^{(1)} ⊗ u_t) + 0.5 G_uu (u_t ⊗ u_t) + 0.5 G_σσ σ²

i.e. states and controls are both rows of Dynare's rule
``y_t = ys + 0.5 ghs2 + ghx x_{t-1} + ghu u_t + 0.5 ghxx (x⊗x) + ghxu (x⊗u)
+ 0.5 ghuu (u⊗u)``, with the quadratic terms evaluated on the first-order
component only.

Because the quadratic forcing term is evaluated strictly on the stationary
first-order state x_t^{(1)}, the pruned simulation is unconditionally stable
and ergodic whenever the first-order transition matrix G is stable (|λ(G)| < 1).

References
----------
Kim, J., Kim, S., Schaumburg, E. and Sims, C.A. (2008). Calculating and using
    second-order accurate solutions of DSGE models. Journal of Economic
    Dynamics and Control, 32(11), 3397-3414.
Andreasen, M.M., Fernández-Villaverde, J. and Rubio-Ramírez, J.F. (2018).
    The Pruned State-Space System for Non-Linear DSGE Models: Theory and
    Empirical Applications. Review of Economic Studies, 85(1), 1-49.
Schmitt-Grohé, S. and Uribe, M. (2004). Solving dynamic general equilibrium
    models using a second-order approximation to the policy function.
    Journal of Economic Dynamics and Control, 28(4), 755-775.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Sequence

import numpy as np
import pandas as pd
import scipy.linalg

from ._results import TheoreticalMomentsResult
from ._moments import conditional_fevd, first_order_moments


@dataclass(frozen=True)
class PrunedSimulationResult:
    """Simulation trajectory generated by second-order pruned perturbation.

    Attributes
    ----------
    states : pd.DataFrame
        Combined state paths x_t = x_t^{(1)} + x_t^{(2)}.
    controls : pd.DataFrame
        Combined control paths y_t = y_t^{(1)} + y_t^{(2)}.
    states_1st : pd.DataFrame
        First-order state component x_t^{(1)}.
    states_2nd : pd.DataFrame
        Second-order state correction x_t^{(2)}.
    controls_1st : pd.DataFrame
        First-order control component y_t^{(1)}.
    controls_2nd : pd.DataFrame
        Second-order control correction y_t^{(2)}.
    shocks : pd.DataFrame
        Simulated innovation paths eps_t.
    """

    states: pd.DataFrame
    controls: pd.DataFrame
    states_1st: pd.DataFrame
    states_2nd: pd.DataFrame
    controls_1st: pd.DataFrame
    controls_2nd: pd.DataFrame
    shocks: pd.DataFrame

    def to_frame(self) -> pd.DataFrame:
        """Concatenate states and controls into a single DataFrame."""
        return pd.concat([self.states, self.controls], axis=1)

    def summary(self) -> str:
        """Summary statistics of the pruned simulation paths."""
        df = self.to_frame()
        desc = df.describe().T[["mean", "std", "min", "50%", "max"]]
        desc.columns = ["Mean", "StdDev", "Min", "Median", "Max"]
        lines = [
            "Pruned DSGE Simulation Summary (Kim et al. 2008)",
            "=" * 72,
            f"Periods Simulated : {len(df)}",
            f"States            : {list(self.states.columns)}",
            f"Controls          : {list(self.controls.columns)}",
            "-" * 72,
            desc.to_string(),
            "=" * 72,
        ]
        return "\n".join(lines)


@dataclass(frozen=True)
class PrunedDSGESolution:
    """Second-order pruned DSGE state-space solution (Dynare timing).

    Attributes
    ----------
    G : np.ndarray
        (n_x, n_x) first-order state transition matrix: ``x_t = G x_{t-1} + N u_t``.
    N : np.ndarray
        (n_x, n_e) first-order state innovation loading.
    F : np.ndarray
        (n_y, n_x) first-order control policy on the *lagged* state:
        ``y_t = F x_{t-1} + L u_t`` (Dynare's ``ghx`` control rows).
    L : np.ndarray
        (n_y, n_e) first-order control innovation loading.
    H_xx : np.ndarray
        (n_x, n_x^2) second-order Hessian matrix for states (Dynare's ``ghxx``
        state rows; the rule applies ``0.5 * H_xx``).
    H_sigmasigma : np.ndarray
        (n_x,) second-order volatility drift vector for states (``ghs2``).
    G_xx : np.ndarray
        (n_y, n_x^2) second-order Hessian matrix for controls.
    G_sigmasigma : np.ndarray
        (n_y,) second-order volatility drift vector for controls.
    state_names : tuple[str, ...]
        Names of predetermined state variables.
    control_names : tuple[str, ...]
        Names of forward-looking control variables.
    shock_names : tuple[str, ...]
        Names of exogenous innovations.
    shock_cov : np.ndarray, optional
        Innovation covariance Σ_u the risk correction was computed with; the
        default covariance for simulations, IRF sizes and moments. Identity
        when not given.
    params : dict, optional
        Parameter values the model was solved with.
    first_order : LinearModel, optional
        The underlying first-order model (``build_dynare`` / ``load_mod``).
    """

    G: np.ndarray
    N: np.ndarray
    F: np.ndarray
    L: np.ndarray
    H_xx: np.ndarray
    H_sigmasigma: np.ndarray
    G_xx: np.ndarray
    G_sigmasigma: np.ndarray
    state_names: tuple[str, ...]
    control_names: tuple[str, ...]
    shock_names: tuple[str, ...]
    H_xu: np.ndarray | None = None
    H_uu: np.ndarray | None = None
    G_xu: np.ndarray | None = None
    G_uu: np.ndarray | None = None
    steady_state: pd.Series | None = None
    variable_names: tuple[str, ...] | None = None
    ghx: np.ndarray | None = None
    ghu: np.ndarray | None = None
    ghxx: np.ndarray | None = None
    ghxu: np.ndarray | None = None
    ghuu: np.ndarray | None = None
    ghs2: np.ndarray | None = None
    shock_cov: np.ndarray | None = None
    params: dict | None = None
    first_order: Any | None = None

    def __post_init__(self):
        n_x, n_y, n_e = self.n_states, self.n_controls, self.n_shocks
        if self.H_xu is None:
            object.__setattr__(self, "H_xu", np.zeros((n_x, n_x * n_e)))
        if self.H_uu is None:
            object.__setattr__(self, "H_uu", np.zeros((n_x, n_e * n_e)))
        if self.G_xu is None:
            object.__setattr__(self, "G_xu", np.zeros((n_y, n_x * n_e)))
        if self.G_uu is None:
            object.__setattr__(self, "G_uu", np.zeros((n_y, n_e * n_e)))
        if self.variable_names is None:
            object.__setattr__(self, "variable_names", self.state_names + self.control_names)
        if self.steady_state is None:
            object.__setattr__(self, "steady_state", pd.Series(0.0, index=self.variable_names))
        if self.ghx is None:
            object.__setattr__(self, "ghx", np.vstack([self.G, self.F]))
        if self.ghu is None:
            object.__setattr__(self, "ghu", np.vstack([self.N, self.L]))
        if self.ghxx is None:
            object.__setattr__(self, "ghxx", np.vstack([self.H_xx, self.G_xx]))
        if self.ghxu is None:
            object.__setattr__(self, "ghxu", np.vstack([self.H_xu, self.G_xu]))
        if self.ghuu is None:
            object.__setattr__(self, "ghuu", np.vstack([self.H_uu, self.G_uu]))
        if self.ghs2 is None:
            object.__setattr__(self, "ghs2", np.concatenate([self.H_sigmasigma, self.G_sigmasigma]))
        if self.shock_cov is None:
            object.__setattr__(self, "shock_cov", np.eye(n_e))
        else:
            cov = np.asarray(self.shock_cov, dtype=float)
            if cov.shape != (n_e, n_e):
                raise ValueError(f"shock_cov must be ({n_e}, {n_e}), got {cov.shape}")
            object.__setattr__(self, "shock_cov", cov)

    # -- sizes and names ---------------------------------------------------

    @property
    def n_states(self) -> int:
        return len(self.state_names)

    @property
    def n_controls(self) -> int:
        return len(self.control_names)

    @property
    def n_shocks(self) -> int:
        return len(self.shock_names)

    @property
    def variables(self) -> tuple[str, ...]:
        """All endogenous variable names in model order (alias of ``variable_names``)."""
        return tuple(self.variable_names or ())

    @property
    def states(self) -> tuple[str, ...]:
        """Predetermined state names (alias of ``state_names``)."""
        return tuple(self.state_names)

    @property
    def controls(self) -> tuple[str, ...]:
        """Control names (alias of ``control_names``)."""
        return tuple(self.control_names)

    @property
    def shocks(self) -> tuple[str, ...]:
        """Innovation names (alias of ``shock_names``)."""
        return tuple(self.shock_names)

    @property
    def eigenvalues(self) -> np.ndarray:
        """Eigenvalues of the first-order state transition matrix G."""
        return scipy.linalg.eigvals(self.G)

    @property
    def is_stable(self) -> bool:
        """Check whether the first-order transition G is strictly stable (|λ| < 1)."""
        return bool(np.all(np.abs(self.eigenvalues) < 1.0 - 1e-7))

    # -- shock helpers -----------------------------------------------------

    def _sigma_u(self, sigma: float, shock_cov: np.ndarray | None) -> np.ndarray:
        """Innovation covariance ``σ² Σ_u`` for a perturbation scale ``sigma``."""
        if isinstance(sigma, Mapping):
            raise TypeError(
                "PrunedDSGESolution takes a scalar perturbation scale `sigma`; a "
                "per-shock mapping changes the risk correction and needs the "
                "equations: use LinearModel.stoch_simul(order=2, sigma=...) or "
                "LinearModel.solve(order=2, shock_cov=...)."
            )
        cov = self._cov() if shock_cov is None else np.asarray(shock_cov, dtype=float)
        return float(sigma) ** 2 * cov

    def _cov(self) -> np.ndarray:
        """Shock covariance, defaulting to the identity when none was declared."""
        if self.shock_cov is None:
            return np.eye(self.n_shocks)
        return np.asarray(self.shock_cov, dtype=float)

    def _shock_sd(self, sigma: float = 1.0) -> np.ndarray:
        return float(sigma) * np.sqrt(np.clip(np.diag(self._cov()), 0.0, None))

    def _var_order(self) -> list[int]:
        """Row indices of ``[states; controls]`` in ``variable_names`` order."""
        ord_names = list(self.state_names) + list(self.control_names)
        return [ord_names.index(v) for v in (self.variable_names or ())]

    def decision_rules(self):
        """Decision rule representation matching Dynare's oo_.dr structure at 2nd order.

        Returns
        -------
        Dynare2ndDR
            Container holding ghx, ghu, ghxx, ghxu, ghuu, ghs2, steady states, and variable labels.
        """
        from ._results import Dynare2ndDR

        v_names = list(self.variable_names)
        s_names = list(self.state_names)
        e_names = list(self.shock_names)

        df_ghx = pd.DataFrame(self.ghx, index=v_names, columns=s_names)
        df_ghu = pd.DataFrame(self.ghu, index=v_names, columns=e_names)

        cols_xx = [f"{s1}_{s2}" for s1 in s_names for s2 in s_names]
        df_ghxx = pd.DataFrame(self.ghxx, index=v_names, columns=cols_xx)

        cols_xu = [f"{s}_{e}" for s in s_names for e in e_names]
        df_ghxu = pd.DataFrame(self.ghxu, index=v_names, columns=cols_xu)

        cols_uu = [f"{e1}_{e2}" for e1 in e_names for e2 in e_names]
        df_ghuu = pd.DataFrame(self.ghuu, index=v_names, columns=cols_uu)

        s_ghs2 = pd.Series(self.ghs2, index=v_names)
        s_ys = (
            self.steady_state.loc[v_names]
            if isinstance(self.steady_state, pd.Series)
            else pd.Series(self.steady_state, index=v_names)
        )

        return Dynare2ndDR(
            ghx=df_ghx,
            ghu=df_ghu,
            ghxx=df_ghxx,
            ghxu=df_ghxu,
            ghuu=df_ghuu,
            ghs2=s_ghs2,
            ys=s_ys,
            state_variables=self.state_names,
            variable_names=self.variable_names,
            shock_names=self.shock_names,
        )

    @property
    def dynare_dr(self):
        """Dynare decision rules property alias."""
        return self.decision_rules()

    @property
    def oo_dr(self):
        """Dynare oo_.dr alias for direct MATLAB/Dynare parity."""
        return self.decision_rules()

    # -- pruned recursion --------------------------------------------------

    def _pruned_path(
        self,
        eps: np.ndarray,
        sigma: float,
        x0: np.ndarray | None = None,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
        """Run the pruned recursion for a given innovation path (Dynare timing).

        ``eps`` has one row per period ``t = 0..T-1``; ``x0`` is the
        first-order state ``x_{-1}`` before the first innovation (steady
        state when None). Returns ``(x1, x2, y1, y2)`` with one row per period.
        """
        eps = np.asarray(eps, dtype=float)
        total_t = eps.shape[0]
        n_x, n_y = self.n_states, self.n_controls
        x1 = np.zeros((total_t, n_x))
        x2 = np.zeros((total_t, n_x))
        y1 = np.zeros((total_t, n_y))
        y2 = np.zeros((total_t, n_y))

        sig2 = float(sigma) ** 2
        half_h_ss = 0.5 * self.H_sigmasigma * sig2
        half_g_ss = 0.5 * self.G_sigmasigma * sig2

        x1_prev = np.zeros(n_x) if x0 is None else np.asarray(x0, dtype=float)
        x2_prev = np.zeros(n_x)
        for t in range(total_t):
            e_t = eps[t]
            kron_xx = np.kron(x1_prev, x1_prev)
            kron_xe = np.kron(x1_prev, e_t)
            kron_ee = np.kron(e_t, e_t)

            x1[t] = self.G @ x1_prev + self.N @ e_t
            x2[t] = (
                self.G @ x2_prev
                + 0.5 * (self.H_xx @ kron_xx)
                + self.H_xu @ kron_xe
                + 0.5 * (self.H_uu @ kron_ee)
                + half_h_ss
            )
            y1[t] = self.F @ x1_prev + self.L @ e_t
            y2[t] = (
                self.F @ x2_prev
                + 0.5 * (self.G_xx @ kron_xx)
                + self.G_xu @ kron_xe
                + 0.5 * (self.G_uu @ kron_ee)
                + half_g_ss
            )
            x1_prev, x2_prev = x1[t], x2[t]
        return x1, x2, y1, y2

    def _draw_shocks(self, total_t: int, sigma: float, seed: int) -> np.ndarray:
        rng = np.random.default_rng(seed)
        n_e = self.n_shocks
        if n_e == 0:
            return np.zeros((total_t, 0))
        cov = self._sigma_u(sigma, None)
        return rng.multivariate_normal(np.zeros(n_e), cov, size=total_t, method="cholesky")

    def simulate(
        self,
        periods: int = 200,
        shocks: np.ndarray | None = None,
        sigma: float = 1.0,
        seed: int = 0,
        burn: int = 100,
    ) -> PrunedSimulationResult:
        """Simulate the model using the Kim et al. (2008) pruning algorithm.

        Parameters
        ----------
        periods : int, default 200
            Number of periods to return after burn-in.
        shocks : np.ndarray, optional
            Pre-specified innovation array of shape (total_periods, n_shocks),
            used as the innovations ``u_t`` directly. If None, drawn as
            i.i.d. Gaussian ``N(0, sigma² Σ_u)`` with ``Σ_u = shock_cov``.
        sigma : float, default 1.0
            Perturbation scale σ: scales the innovations' standard deviation
            and the risk-correction terms ``0.5 ghs2 σ²`` consistently.
        seed : int, default 0
            Random seed when shocks is None.
        burn : int, default 100
            Number of initial burn-in periods discarded to eliminate transient start.

        Returns
        -------
        PrunedSimulationResult
            Container with state and control paths (both total and pruned 1st/2nd components).
        """
        if not self.is_stable:
            raise ValueError(
                "First-order state transition G has eigenvalues outside the unit circle; "
                "model is explosive."
            )

        total_t = periods + burn
        n_e = self.n_shocks

        if shocks is None:
            eps = self._draw_shocks(total_t, sigma, seed)
        else:
            eps_arr = np.asarray(shocks, dtype=float)
            if eps_arr.ndim != 2 or eps_arr.shape[0] < total_t or eps_arr.shape[1] != n_e:
                raise ValueError(
                    f"shocks shape {eps_arr.shape} incompatible with total_t={total_t}, n_shocks={n_e}"
                )
            eps = eps_arr[:total_t]

        x1, x2, y1, y2 = self._pruned_path(eps, sigma)

        # Slice after burn-in
        x_tot = x1[burn:] + x2[burn:]
        y_tot = y1[burn:] + y2[burn:]

        idx = pd.RangeIndex(start=0, stop=periods, name="t")
        df_states = pd.DataFrame(x_tot, index=idx, columns=self.state_names)
        df_controls = pd.DataFrame(y_tot, index=idx, columns=self.control_names)
        df_x1 = pd.DataFrame(x1[burn:], index=idx, columns=self.state_names)
        df_x2 = pd.DataFrame(x2[burn:], index=idx, columns=self.state_names)
        df_y1 = pd.DataFrame(y1[burn:], index=idx, columns=self.control_names)
        df_y2 = pd.DataFrame(y2[burn:], index=idx, columns=self.control_names)
        df_eps = pd.DataFrame(eps[burn:], index=idx, columns=self.shock_names)

        return PrunedSimulationResult(
            states=df_states,
            controls=df_controls,
            states_1st=df_x1,
            states_2nd=df_x2,
            controls_1st=df_y1,
            controls_2nd=df_y2,
            shocks=df_eps,
        )

    def simulate_raw(
        self,
        periods: int = 200,
        shocks: np.ndarray | None = None,
        sigma: float = 1.0,
        seed: int = 0,
        burn: int = 100,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Simulate without pruning to demonstrate explosive instability.

        Warning: Standard second-order perturbation without pruning easily explodes
        to +/- inf for larger shocks or long horizons.
        """
        total_t = periods + burn
        n_x, n_y, n_e = self.n_states, self.n_controls, self.n_shocks

        if shocks is None:
            eps = self._draw_shocks(total_t, sigma, seed)
        else:
            eps = np.asarray(shocks, dtype=float)[:total_t]

        x = np.zeros((total_t, n_x))
        y = np.zeros((total_t, n_y))

        sig2 = float(sigma) ** 2
        half_h_ss = 0.5 * self.H_sigmasigma * sig2
        half_g_ss = 0.5 * self.G_sigmasigma * sig2

        x_prev = np.zeros(n_x)
        for t in range(total_t):
            e_t = eps[t]
            # Raw unpruned quadratic feedback: evaluated on the raw lagged state.
            # Clip if already overflowed to avoid numerical crash
            if np.any(np.abs(x_prev) > 1e8):
                x[t:] = np.nan
                y[t:] = np.nan
                break

            kron_xx = np.kron(x_prev, x_prev)
            kron_xe = np.kron(x_prev, e_t)
            kron_ee = np.kron(e_t, e_t)

            x[t] = (
                self.G @ x_prev + self.N @ e_t
                + 0.5 * (self.H_xx @ kron_xx) + self.H_xu @ kron_xe
                + 0.5 * (self.H_uu @ kron_ee) + half_h_ss
            )
            y[t] = (
                self.F @ x_prev + self.L @ e_t
                + 0.5 * (self.G_xx @ kron_xx) + self.G_xu @ kron_xe
                + 0.5 * (self.G_uu @ kron_ee) + half_g_ss
            )
            x_prev = x[t]

        return x[burn:], y[burn:]

    def girf(
        self,
        shock: int | str = 0,
        size: float = 1.0,
        horizon: int = 20,
        sigma: float = 1.0,
        x0: np.ndarray | None = None,
    ) -> pd.DataFrame:
        """Generalized Impulse Response Function (GIRF) under pruning.

        In non-linear models, responses depend on the sign and scale of the shock
        as well as the initial state. The GIRF computes:
            GIRF_h = E[ z_h | u_0 = size, x_{-1} ] - E[ z_h | u_0 = 0, x_{-1} ]

        with the innovation hitting at ``h = 0`` so that, as in Dynare's
        ``oo_.irfs``, row ``0`` is the impact period for states and controls
        alike.

        Parameters
        ----------
        shock : int or str, default 0
            Index or name of the innovation to shock.
        size : float, default 1.0
            Magnitude of the innovation at h=0 (in the units of ``u_t``).
        horizon : int, default 20
            Number of periods after impact.
        sigma : float, default 1.0
            Perturbation parameter scale σ for the risk-correction terms.
        x0 : np.ndarray, optional
            First-order state before impact, ``x_{-1}`` (defaults to steady state = 0).

        Returns
        -------
        pd.DataFrame
            Impulse responses for all states and controls, indexed by horizon 0..horizon.
        """
        if isinstance(shock, str):
            if shock not in self.shock_names:
                raise ValueError(
                    f"unknown shock {shock!r}; available: {self.shock_names}"
                )
            s_idx = self.shock_names.index(shock)
        else:
            s_idx = int(shock)

        n_e = self.n_shocks
        t_steps = horizon + 1

        eps_base = np.zeros((t_steps, n_e))
        eps_shock = np.zeros((t_steps, n_e))
        eps_shock[0, s_idx] = size

        def run_path(e_mat: np.ndarray) -> np.ndarray:
            x1, x2, y1, y2 = self._pruned_path(e_mat, sigma, x0=x0)
            return np.hstack([x1 + x2, y1 + y2])

        diff = run_path(eps_shock) - run_path(eps_base)

        cols = list(self.state_names) + list(self.control_names)
        return pd.DataFrame(diff, index=pd.RangeIndex(t_steps, name="h"), columns=cols)

    def irf(
        self,
        shock: int | str = 0,
        horizon: int = 20,
        size: float = 1.0,
        sigma: float = 0.0,
        x0: np.ndarray | None = None,
    ) -> pd.DataFrame:
        """Impulse responses for the 2nd-order pruned model around steady state.

        Parameters
        ----------
        shock : int or str, default 0
            Index or name of the innovation to shock.
        horizon : int, default 20
            Number of periods after impact.
        size : float, default 1.0
            Magnitude of innovation.
        sigma : float, default 0.0
            Perturbation parameter scale σ. Default 0.0 evaluates deterministic
            impulse responses starting from deterministic steady state.
        x0 : np.ndarray, optional
            Initial state vector.

        Returns
        -------
        pd.DataFrame
            Impulse responses ordered by self.variable_names, indexed by horizon 0..horizon.
        """
        df = self.girf(shock=shock, size=size, horizon=horizon, sigma=sigma, x0=x0)
        vars_tuple = self.variable_names if self.variable_names is not None else (self.state_names + self.control_names)
        cols = [v for v in vars_tuple if v in df.columns]
        return df[cols]

    def plot(
        self,
        shock: int | str = 0,
        size: float = 1.0,
        horizon: int = 20,
        sigma: float = 1.0,
        variables: Sequence[str] | None = None,
        *,
        ax=None,
        title: str = "",
        ylabel: str = "GIRF Response",
    ):
        """Plot pruned Generalized Impulse Response Functions (GIRF)."""
        from ..plot import _new_ax

        df = self.girf(shock=shock, size=size, horizon=horizon, sigma=sigma)
        if variables is not None:
            vars_to_plot = [v for v in variables if v in df.columns]
        else:
            vars_to_plot = list(df.columns)

        fig, ax = _new_ax(ax)
        for col in vars_to_plot:
            ax.plot(df.index, df[col], label=col, linewidth=1.2)

        ax.axhline(0.0, color="0.3", linewidth=0.6, linestyle=":")
        ax.set_xlabel("Horizon (h)")
        ax.set_ylabel(ylabel)
        if not title:
            s_name = shock if isinstance(shock, str) else self.shock_names[shock]
            title = f"Pruned DSGE GIRF to {s_name} shock"
        ax.set_title(title)
        ax.legend(loc="best", frameon=False)
        return fig

    def stochastic_steady_state(
        self, sigma: float = 1.0, shock_cov: np.ndarray | None = None
    ) -> dict[str, pd.Series]:
        """Compute the analytical pruned ergodic mean (second-order risk-adjusted steady state).

        Parameters
        ----------
        sigma : float, default 1.0
            Perturbation parameter scale σ.
        shock_cov : np.ndarray, optional
            Covariance matrix of innovations Σ_u (defaults to ``self.shock_cov``).

        Returns
        -------
        dict[str, pd.Series]
            Ergodic mean deviations from the deterministic steady state for
            states and controls.
        """
        n_x = self.n_states
        sigma_e = self._sigma_u(sigma, shock_cov)

        # Solve discrete Lyapunov equation for 1st-order state variance:
        # Omega = G @ Omega @ G.T + N @ sigma_e @ N.T
        q_mat = self.N @ sigma_e @ self.N.T
        omega = scipy.linalg.solve_discrete_lyapunov(self.G, q_mat)

        # E[x_{t-1}^{(1)} ⊗ x_{t-1}^{(1)}] = vec(omega), E[u ⊗ u] = vec(sigma_e);
        # the cross term E[x_{t-1} ⊗ u_t] vanishes (Dynare timing).
        vec_omega = omega.flatten()
        vec_se = sigma_e.flatten()
        sig2 = float(sigma) ** 2
        # E[x_t^{(2)}] = (I - G)^(-1) [ 0.5 H_xx vec(omega) + 0.5 H_uu vec(sigma_e) + 0.5 H_ss σ² ]
        i_minus_g = np.eye(n_x) - self.G
        rhs_x = (
            0.5 * (self.H_xx @ vec_omega)
            + 0.5 * (self.H_uu @ vec_se)
            + 0.5 * self.H_sigmasigma * sig2
        )
        mu_x2 = scipy.linalg.solve(i_minus_g, rhs_x)

        # E[y_t] = F E[x2] + 0.5 G_xx vec(omega) + 0.5 G_uu vec(sigma_e) + 0.5 G_ss σ²
        mu_y = (
            self.F @ mu_x2
            + 0.5 * (self.G_xx @ vec_omega)
            + 0.5 * (self.G_uu @ vec_se)
            + 0.5 * self.G_sigmasigma * sig2
        )

        return {
            "states": pd.Series(mu_x2, index=self.state_names, name="ergodic_mean_states"),
            "controls": pd.Series(mu_y, index=self.control_names, name="ergodic_mean_controls"),
        }

    def theoretical_moments(
        self,
        sigma: float = 1.0,
        shock_cov: np.ndarray | None = None,
        lags: int = 4,
        fevd_horizons: Sequence[int | None] = (1, 4, 8, 16, 32, None),
    ) -> TheoreticalMomentsResult:
        """Compute analytical theoretical moments matching Dynare's stoch_simul.

        Under the pruned second-order approximation the second moments are
        those of the first-order component (cross-order expectations vanish
        or enter at fourth order), so covariances, correlations,
        autocorrelations and the variance decomposition coincide with
        :meth:`LinearModel.theoretical_moments` for the same first-order
        rules and shock covariance. The means carry the second-order
        risk adjustment from :meth:`stochastic_steady_state`.

        Parameters
        ----------
        sigma : float, default 1.0
            Perturbation scale σ (scales the innovation standard deviations).
        shock_cov : np.ndarray, optional
            Covariance matrix of innovations (n_e x n_e). Default ``self.shock_cov``.
        lags : int, default 4
            Number of autocorrelation lags to report.
        fevd_horizons : Sequence[int | None], default (1, 4, 8, 16, 32, None)
            Horizons for the conditional variance decomposition (None = asymptotic).

        Returns
        -------
        TheoreticalMomentsResult
            Analytical moments [Mean, Std.Dev., Variance], correlation matrix,
            autocorrelation matrix, and variance decomposition (percent).
        """
        sigma_e = self._sigma_u(sigma, shock_cov)
        M_x = np.vstack([self.G, self.F])
        M_u = np.vstack([self.N, self.L])
        _, gamma_0, gammas = first_order_moments(self.G, self.N, M_x, M_u, sigma_e, lags)

        order = self._var_order()
        all_names = list(self.variable_names or ())
        cov_mat = gamma_0[np.ix_(order, order)]

        sss = self.stochastic_steady_state(sigma=sigma, shock_cov=shock_cov)
        ss_base = (
            self.steady_state
            if isinstance(self.steady_state, pd.Series)
            else pd.Series(0.0, index=all_names)
        )
        mean_vec = np.zeros(len(all_names))
        for i, v in enumerate(all_names):
            base_val = float(ss_base.get(v, 0.0))
            if v in self.state_names:
                mean_vec[i] = base_val + float(sss["states"][v])
            elif v in self.control_names:
                mean_vec[i] = base_val + float(sss["controls"][v])
            else:
                mean_vec[i] = base_val

        variances = np.diag(cov_mat)
        stds = np.sqrt(np.maximum(variances, 0.0))

        df_moments = pd.DataFrame(
            {"Mean": mean_vec, "Std.Dev.": stds, "Variance": variances},
            index=all_names,
        )

        std_outer = np.outer(stds, stds)
        std_outer[std_outer == 0.0] = np.nan
        corr_mat = cov_mat / std_outer
        np.fill_diagonal(corr_mat, 1.0)

        df_cov = pd.DataFrame(cov_mat, index=all_names, columns=all_names)
        df_corr = pd.DataFrame(corr_mat, index=all_names, columns=all_names)

        autocorr_cols = [f"Lag {k}" for k in range(1, lags + 1)]
        df_autocorr = pd.DataFrame(index=all_names, columns=autocorr_cols, dtype=float)
        for k, gamma_k in enumerate(gammas, start=1):
            diag_k = np.diag(gamma_k[np.ix_(order, order)])
            with np.errstate(divide="ignore", invalid="ignore"):
                df_autocorr[f"Lag {k}"] = np.where(variances > 1e-14, diag_k / variances, np.nan)

        sd = np.sqrt(np.clip(np.diag(sigma_e), 0.0, None))
        C = np.asarray(self.ghx, dtype=float)
        D = np.asarray(self.ghu, dtype=float)
        df_fevd = conditional_fevd(
            self.G, self.N, C, D, sd, list(fevd_horizons), all_names, list(self.shock_names)
        ) * 100.0

        return TheoreticalMomentsResult(
            moments=df_moments,
            covariance=df_cov,
            correlation=df_corr,
            autocorr=df_autocorr,
            fevd=df_fevd,
        )

    def stoch_simul(
        self,
        *,
        order: int = 2,
        irf: int = 40,
        periods: int = 0,
        sigma: float = 1.0,
        seed: int = 0,
        burn: int = 100,
        lags: int = 5,
    ):
        """Execute Dynare-compatible 2nd-order stoch_simul routine.

        Computes:
        1. Second-order decision rules (oo_.dr)
        2. Theoretical unconditional moments under pruning (with volatility risk correction)
        3. Impulse response functions to a one-standard-deviation innovation in each shock
        4. Simulated sample moments (if periods > 0)

        Parameters
        ----------
        order : int, default 2
            Approximation order (must be 2).
        irf : int, default 40
            Horizon for impulse response functions. Set to 0 to skip IRFs.
        periods : int, default 0
            Number of simulation periods. If > 0, generates simulated moments.
        sigma : float, default 1.0
            Perturbation scale σ applied to the declared shock covariance
            ``shock_cov`` (innovations ``N(0, σ² Σ_u)``, IRFs of size
            ``σ sqrt(Σ_u[j, j])``). A per-shock mapping is rejected: it
            changes the risk correction, so re-solve through
            ``LinearModel.stoch_simul(order=2, sigma=...)`` instead.
        seed : int, default 0
            RNG seed for simulation when periods > 0.
        burn : int, default 100
            Burn-in periods dropped before calculating simulated moments.
        lags : int, default 5
            Number of autocorrelation lags.

        Returns
        -------
        StochSimulResult
            Container holding dr, theoretical_moments, simulated_moments, irfs, and export methods.
        """
        from ._results import StochSimulResult

        if order != 2:
            raise ValueError(f"PrunedDSGESolution only supports order=2, got order={order}")
        if isinstance(sigma, Mapping):
            self._sigma_u(sigma, None)  # raises the explanatory TypeError

        dr = self.decision_rules()
        theo = self.theoretical_moments(sigma=sigma, lags=lags)

        vars_tuple = self.variable_names if self.variable_names is not None else (self.state_names + self.control_names)
        sd = self._shock_sd(sigma)
        irfs: dict[str, pd.Series] = {}
        if irf > 0:
            for j, sh in enumerate(self.shock_names):
                df_irf = self.irf(shock=sh, horizon=irf, size=float(sd[j]), sigma=0.0)
                for v in vars_tuple:
                    irfs[f"{v}_{sh}"] = df_irf[v]

        sim_moments = None
        if periods > 0:
            sim_res = self.simulate(periods=periods, sigma=sigma, seed=seed, burn=burn)
            sim_df = pd.concat([sim_res.states, sim_res.controls], axis=1)[list(vars_tuple)]
            sim_moments = pd.DataFrame(
                {
                    "Mean": sim_df.mean(axis=0),
                    "Std.Dev.": sim_df.std(axis=0),
                    "Variance": sim_df.var(axis=0),
                    "Skewness": sim_df.skew(axis=0),
                    "Kurtosis": sim_df.kurtosis(axis=0),
                },
                index=list(vars_tuple),
            )

        return StochSimulResult(
            dr=dr,
            theoretical_moments=theo,
            simulated_moments=sim_moments,
            irfs=irfs,
            order=2,
            variable_names=vars_tuple,
            shock_names=self.shock_names,
        )


def canonical_growth_2nd_order(
    alpha: float = 0.33,
    beta: float = 0.99,
    delta: float = 0.025,
    sigma_pref: float = 1.0,
    rho: float = 0.95,
    sigma_eps: float = 0.01,
) -> PrunedDSGESolution:
    """Solve the canonical one-sector growth model to second order with pruning.

    The benchmark of Kim, Kim, Schaumburg & Sims (2008):

      max E_0 sum beta^t (c_t^{1-sigma_pref} - 1) / (1 - sigma_pref)
      s.t. c_t + k_t - (1 - delta) k_{t-1} = z_t k_{t-1}^alpha
           ln z_t = rho ln z_{t-1} + sigma_eps * eps_t,   eps_t ~ N(0, 1)

    written in log deviations (``k = ln K``, ``c = ln C``, ``z = ln Z``) so
    that every decision-rule coefficient reads as an elasticity. The model
    is solved with :func:`puremacro.dsge.solve_dynare_2nd_order`, i.e. the
    matrices are the genuine second-order perturbation, not a calibration.

    Returns
    -------
    PrunedDSGESolution
        States ``("k", "z")``, control ``("c",)``, shock ``("eps",)``, with
        ``shock_cov = [[1.0]]`` (the shock scale ``sigma_eps`` sits inside
        the technology equation).
    """
    from puremacro.dsge.dynare import solve_dynare_2nd_order

    r_ss = 1.0 / beta - (1.0 - delta)
    k_ss = (r_ss / alpha) ** (1.0 / (alpha - 1.0))
    c_ss = k_ss**alpha - delta * k_ss

    def growth(lead, curr, lag, shocks, p):
        return [
            np.exp(-p.sigma_pref * curr.c)
            - p.beta * np.exp(-p.sigma_pref * lead.c)
            * (p.alpha * np.exp(lead.z) * np.exp((p.alpha - 1.0) * curr.k) + 1.0 - p.delta),
            np.exp(curr.c) + np.exp(curr.k)
            - np.exp(curr.z) * np.exp(p.alpha * lag.k) - (1.0 - p.delta) * np.exp(lag.k),
            curr.z - p.rho * lag.z - p.sigma_eps * shocks.eps,
        ]

    return solve_dynare_2nd_order(
        growth,
        variables=["k", "z", "c"],
        shocks=["eps"],
        params=dict(alpha=alpha, beta=beta, delta=delta, sigma_pref=sigma_pref,
                    rho=rho, sigma_eps=sigma_eps),
        steady_state=dict(k=float(np.log(k_ss)), z=0.0, c=float(np.log(c_ss))),
        states=["k", "z"],
        shock_cov=np.eye(1),
    )
