"""Skew-t conditional density fitting — the ABG 2019 step that turns
predicted quantiles into a smooth distribution.

Adrian-Boyarchenko-Giannone fit the four parameters (μ, σ, α, ν) of
Azzalini's skew-t by **quantile-matching**: minimise the squared
distance between the predicted quantiles ``Q_τ`` (e.g. from a quantile
LP at horizons 1 and 4) and the skew-t inverse CDF evaluated at the
same τ. The fitted density gives:

  - ``downside_5pct(F)``  = Q_0.05(F)        (the canonical "5 % GaR")
  - ``upside_95pct(F)``   = Q_0.95(F)
  - ``expected_shortfall_5pct(F)`` = E[Y | Y ≤ Q_0.05]
  - ``downside_entropy(F)`` per ABG 2019 measuring asymmetry of the lower tail

The Azzalini skew-t PDF (Azzalini-Capitanio 2003) is

    f(x) = (2 / σ) · t_ν(z) · T_{ν+1}(α z √((ν+1) / (ν + z²))),
    z = (x − μ) / σ,

where t_ν is the t-density and T_{ν+1} is the t-CDF. CDF and quantiles
are obtained numerically.

References
----------
Adrian, T., Boyarchenko, N. and Giannone, D. (2019). Vulnerable growth.
    AER 109(4), 1263-1289.
Azzalini, A. and Capitanio, A. (2003). Distributions generated by
    perturbation of symmetry with emphasis on a multivariate skew t
    distribution. JRSS-B 65(2), 367-389.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import numpy as np

# NumPy compatibility: np.trapz removed in 2.0 → np.trapezoid; older
# versions only have np.trapz. Shim covers both. (Note: getattr's default
# is evaluated eagerly, so a bare `getattr(np, "trapezoid", np.trapz)`
# raises if np.trapz is missing — use hasattr instead.)
if hasattr(np, "trapezoid"):
    _trapz = np.trapezoid
elif hasattr(np, "trapz"):
    _trapz = np.trapz
else:
    raise ImportError("Neither np.trapezoid nor np.trapz is available; need NumPy >= 1.x")
from scipy.optimize import minimize, brentq
from scipy.stats import t as student_t


# ---------------------------------------------------------------------------
# Skew-t basic functions
# ---------------------------------------------------------------------------


def skewt_pdf(
    x: np.ndarray | float,
    mu: float, sigma: float, alpha: float, nu: float,
) -> np.ndarray:
    """Azzalini skew-t probability density.

    Parameters
    ----------
    x : ndarray or float
        Evaluation points.
    mu : float
        Location parameter.
    sigma : float
        Scale parameter (must be positive; clamped to ``>= 1e-8``).
    alpha : float
        Skewness parameter (0 ⇒ symmetric Student-t).
    nu : float
        Degrees-of-freedom parameter (clamped to ``>= 2.5`` for finite
        variance).

    Returns
    -------
    ndarray
        Density values at ``x``.
    """
    sigma = max(float(sigma), 1e-8)
    nu = max(float(nu), 2.5)
    z = (np.asarray(x, dtype=float) - mu) / sigma
    base = student_t.pdf(z, df=nu) / sigma
    factor_arg = alpha * z * np.sqrt((nu + 1.0) / (nu + z ** 2))
    skew_factor = student_t.cdf(factor_arg, df=nu + 1.0)
    return 2.0 * base * skew_factor


def skewt_cdf(
    x: np.ndarray | float,
    mu: float, sigma: float, alpha: float, nu: float,
) -> np.ndarray:
    """Skew-t CDF via numerical quadrature.

    Uses a Simpson's-rule integral of the PDF on a wide left tail; fast
    and accurate enough for quantile-matching use.

    Parameters
    ----------
    x : ndarray or float
        Evaluation points.
    mu, sigma, alpha, nu : float
        Skew-t parameters; see :func:`skewt_pdf`.

    Returns
    -------
    ndarray
        CDF values clipped to ``[0, 1]``.
    """
    x = np.asarray(x, dtype=float).ravel()
    out = np.empty_like(x)
    sigma_safe = max(float(sigma), 1e-8)
    lo = mu - 50.0 * sigma_safe
    n_grid = 600
    for i, xi in enumerate(x):
        if xi <= lo:
            out[i] = 0.0
            continue
        zs = np.linspace(lo, xi, n_grid)
        pdf_vals = skewt_pdf(zs, mu, sigma, alpha, nu)
        # Trapezoidal rule. (np.trapz was removed in NumPy 2.0;
        # np.trapezoid is the rename.)
        out[i] = float(_trapz(pdf_vals, zs))
    return np.clip(out, 0.0, 1.0)


def skewt_ppf(
    tau: float,
    mu: float, sigma: float, alpha: float, nu: float,
    *,
    x_lo: float | None = None,
    x_hi: float | None = None,
) -> float:
    """Skew-t inverse CDF via root-finding on :func:`skewt_cdf`.

    Parameters
    ----------
    tau : float
        Probability level in ``(0, 1)``.
    mu, sigma, alpha, nu : float
        Skew-t parameters; see :func:`skewt_pdf`.
    x_lo, x_hi : float, optional
        Initial bracket for ``brentq``; defaults to ``mu ± 30 σ`` and
        widened automatically if the root is not bracketed.

    Returns
    -------
    float
        ``Q_tau`` — the τ-quantile of the skew-t distribution.
    """
    sigma_safe = max(float(sigma), 1e-8)
    if x_lo is None:
        x_lo = mu - 30.0 * sigma_safe
    if x_hi is None:
        x_hi = mu + 30.0 * sigma_safe

    def root(x):
        return float(skewt_cdf(np.array([x]), mu, sigma, alpha, nu)[0]) - tau

    try:
        return float(brentq(root, x_lo, x_hi, xtol=1e-6))
    except ValueError:
        # Distribution may have shifted outside [x_lo, x_hi]; widen.
        return float(brentq(root, mu - 100 * sigma_safe,
                              mu + 100 * sigma_safe, xtol=1e-6))


# ---------------------------------------------------------------------------
# ABG 2019 quantile-matching fit
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SkewTFit:
    """Result of an Azzalini skew-t fit.

    Attributes
    ----------
    mu, sigma, alpha, nu : float
        Fitted location / scale / skewness / d.o.f. parameters.
    target_quantiles : dict
        The ``{tau: predicted Q_tau}`` mapping the fit was matched
        against (kept for diagnostics).
    success : bool
        ``scipy.optimize.minimize`` convergence flag.
    """

    mu: float
    sigma: float
    alpha: float
    nu: float
    target_quantiles: dict   # {tau: predicted Q_tau}
    success: bool

    def pdf(self, x: np.ndarray | float) -> np.ndarray:
        """Density at ``x`` for the fitted parameters."""
        return skewt_pdf(x, self.mu, self.sigma, self.alpha, self.nu)

    def cdf(self, x: np.ndarray | float) -> np.ndarray:
        """CDF at ``x`` for the fitted parameters."""
        return skewt_cdf(x, self.mu, self.sigma, self.alpha, self.nu)

    def ppf(self, tau: float) -> float:
        """Quantile ``Q_tau`` for the fitted parameters."""
        return skewt_ppf(tau, self.mu, self.sigma, self.alpha, self.nu)

    def downside_quantile(self, tau: float = 0.05) -> float:
        """Conditional quantile at ``tau`` (default 5%)."""
        return self.ppf(tau)

    def expected_shortfall(self, tau: float = 0.05, *, n_grid: int = 500) -> float:
        """Expected shortfall ``E[Y | Y ≤ Q_tau]``.

        Computed by trapezoidal integration of ``x f(x)`` on
        ``[Q_low, Q_tau]`` divided by ``tau``.

        Parameters
        ----------
        tau : float, default 0.05
            Tail probability.
        n_grid : int, default 500
            Number of integration nodes.

        Returns
        -------
        float
            The expected shortfall.
        """
        q = self.ppf(tau)
        xs = np.linspace(self.mu - 30 * self.sigma, q, n_grid)
        f = self.pdf(xs)
        num = float(np.trapezoid(xs * f, xs))
        return num / max(tau, 1e-12)

    def downside_entropy(self, *, n_grid: int = 500) -> float:
        """ABG 2019 measure of lower-tail mass.

        Integral of ``-log f(x) · f(x)`` on the lower half of the
        distribution (from ``mu - 30 σ`` to the median).

        Parameters
        ----------
        n_grid : int, default 500
            Number of integration nodes.

        Returns
        -------
        float
            Lower-tail entropy.
        """
        q_med = self.ppf(0.5)
        xs = np.linspace(self.mu - 30 * self.sigma, q_med, n_grid)
        f = np.maximum(self.pdf(xs), 1e-12)
        return float(np.trapezoid(-np.log(f) * f, xs))


def fit_skewt_to_quantiles(
    quantile_dict: dict[float, float],
    *,
    init: tuple[float, float, float, float] | None = None,
    maxiter: int = 200,
) -> SkewTFit:
    """ABG-style skew-t fit by quantile matching.

    Finds ``(μ, σ, α, ν)`` minimising

        ``Σ_τ (F^{-1}(τ; μ, σ, α, ν) − Q_τ_predicted)²``

    over the predicted quantiles.

    Parameters
    ----------
    quantile_dict : dict[float, float]
        Mapping ``τ → Q_τ_predicted`` (e.g. ``{0.05: -3.2, 0.25: -0.8,
        0.5: 1.5, 0.75: 2.7, 0.95: 4.1}``).
    init : tuple of float, optional
        Starting point ``(μ, σ, α, ν)``. Defaults to a symmetric
        Gaussian-like guess derived from the median and IQR of the
        target quantiles.
    maxiter : int, default 200
        Nelder-Mead iteration cap.

    Returns
    -------
    SkewTFit
        Fitted parameters and convergence flag (see :class:`SkewTFit`).
    """
    taus = np.array(sorted(quantile_dict.keys()), dtype=float)
    qs = np.array([quantile_dict[t] for t in taus], dtype=float)

    if init is None:
        med = float(np.interp(0.5, taus, qs))
        q1 = float(np.interp(0.25, taus, qs))
        q3 = float(np.interp(0.75, taus, qs))
        sigma0 = max((q3 - q1) / 1.349, 1e-3)        # IQR / 1.349 ≈ Gaussian σ
        init = (med, sigma0, 0.0, 8.0)

    def obj(theta):
        mu, sigma, alpha, nu = theta
        if sigma <= 1e-6 or nu <= 2.5 or abs(alpha) > 50:
            return 1e6
        loss = 0.0
        for tau, q in zip(taus, qs):
            try:
                q_hat = skewt_ppf(tau, mu, sigma, alpha, nu)
            except (ValueError, RuntimeError):
                # Bracket failure / non-finite CDF on the brentq inverter
                # is a legitimate "out-of-region" signal — penalise. We
                # narrowed from bare ``except Exception`` because the
                # broader catch previously masked a numpy 2.0 API break
                # (``np.trapz`` removal) by silently returning 1e6 for
                # every parameter vector.
                return 1e6
            loss += (q_hat - q) ** 2
        return float(loss)

    res = minimize(obj, np.asarray(init), method="Nelder-Mead",
                    options={"maxiter": maxiter, "xatol": 1e-5,
                             "fatol": 1e-7})
    mu, sigma, alpha, nu = res.x
    return SkewTFit(
        mu=float(mu), sigma=max(float(sigma), 1e-6),
        alpha=float(alpha), nu=max(float(nu), 2.5),
        target_quantiles=dict(quantile_dict),
        success=bool(res.success),
    )


__all__ = [
    "skewt_pdf", "skewt_cdf", "skewt_ppf",
    "SkewTFit", "fit_skewt_to_quantiles",
]
