"""Juno / Pyodide to Google Colab task offloading bridge.

Allows users working on an iPad (Juno) or in browser environments (Pyodide)
to export heavy compute jobs (MCMC chains, large bootstrap replications,
high-dimensional FAVAR, VFI grid searches) into self-contained Google Colab
notebooks with built-in Google account authentication and Google Drive syncing.
"""
from __future__ import annotations

import base64
import io
import json
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence

import numpy as np


def colab_auth_guide() -> str:
    """Return step-by-step instructions for Google Colab authentication on iPad/mobile."""
    return (
        "Google Colab Authentication & Offloading Guide for iPad / Juno:\n"
        "===============================================================\n"
        "1. Open the generated notebook in Safari or Google Chrome by navigating to:\n"
        "   https://colab.research.google.com\n"
        "2. Tap 'Upload' and select your exported .ipynb notebook.\n"
        "3. When prompted in the notebook, run the authentication cell:\n"
        "   >>> from google.colab import auth\n"
        "   >>> auth.authenticate_user()\n"
        "   A Google sign-in modal will pop up. Select your Google account and grant access.\n"
        "4. (Optional) To persist results directly to your Google Drive, run:\n"
        "   >>> from google.colab import drive\n"
        "   >>> drive.mount('/content/drive')\n"
        "5. Execute the computation cells. Colab's cloud CPUs/GPUs will run the task.\n"
        "6. The notebook saves results as a portable .pmz cartridge that syncs back\n"
        "   to your iPad or local machine via Google Drive or direct download."
    )


def generate_colab_notebook(
    code: str,
    *,
    data_payloads: Mapping[str, Any] | None = None,
    title: str = "puremacro Cloud Compute Task",
    save_path: str | Path | None = "colab_task.ipynb",
    mount_drive: bool = True,
    use_accelerator: bool = False,
    pip_extras: Sequence[str] | None = None,
) -> dict:
    """Generate a self-contained Jupyter notebook tailored for execution in Google Colab.

    Parameters
    ----------
    code : str
        Python code to execute in Google Colab.
    data_payloads : dict, optional
        Mapping of filename -> DataFrame or ndarray. These datasets will be
        embedded directly into the notebook as base64-encoded strings, so the
        Colab session runs 100% offline without manual file uploads.
    title : str, default "puremacro Cloud Compute Task"
        Title for the Colab notebook.
    save_path : str or Path, optional
        Path where the .ipynb file will be saved on disk.
    mount_drive : bool, default True
        If True, includes cells to authenticate and mount Google Drive.
    use_accelerator : bool, default False
        If True, configures the notebook to install numba/accelerator extras.
    pip_extras : sequence of str, optional
        Additional pip extras, e.g. ["backend", "dev"].

    Returns
    -------
    dict
        Jupyter Notebook structure as a dict.
    """
    cells = []

    # Cell 1: Markdown Introduction & Guide
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            f"# {title}\n",
            "\n",
            "This notebook was generated by **puremacro** to offload heavy macroeconomic computation\n",
            "(long bootstraps, MCMC, high-dimensional factor models, or DSGE solving) to Google Colab.\n",
            "\n",
            "### Instructions:\n",
            "1. Run the setup cell below to install `puremacro`.\n",
            "2. If needed, authenticate your Google account to save output to Google Drive.\n",
            "3. Run the analysis cells.\n",
        ],
    })

    # Cell 2: Installation
    extras_str = ""
    if pip_extras:
        extras_str = f"[{','.join(pip_extras)}]"
    elif use_accelerator:
        extras_str = "[backend]"

    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 1. Install puremacro in the Colab cloud environment\n",
            f"!pip install -q 'puremacro{extras_str}'\n",
        ],
    })

    # Cell 3: Google Account Authentication & Drive (optional)
    if mount_drive:
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Authenticate Google Account & Mount Google Drive\n",
                "try:\n",
                "    from google.colab import auth, drive\n",
                "    print('Authenticating Google account...')\n",
                "    auth.authenticate_user()\n",
                "    print('Mounting Google Drive at /content/drive...')\n",
                "    drive.mount('/content/drive')\n",
                "    print('Authentication and Drive mount complete.')\n",
                "except Exception as e:\n",
                "    print(f'Drive mount skipped or running outside Colab: {e}')\n",
            ],
        })

    # Cell 4: Embedded Data Payloads (if any)
    if data_payloads:
        payload_lines = [
            "# 3. Unpack embedded data payloads\n",
            "import io\n",
            "import base64\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "\n",
        ]
        for name, obj in data_payloads.items():
            if hasattr(obj, "to_csv"):
                csv_bytes = obj.to_csv().encode("utf-8")
                b64 = base64.b64encode(csv_bytes).decode("ascii")
                payload_lines.append(f"# Data: {name}\n")
                payload_lines.append(f"{name}_b64 = '{b64}'\n")
                payload_lines.append(
                    f"{name} = pd.read_csv(io.StringIO(base64.b64decode({name}_b64).decode('utf-8')))\n"
                )
            elif isinstance(obj, np.ndarray):
                bio = io.BytesIO()
                np.save(bio, obj)
                b64 = base64.b64encode(bio.getvalue()).decode("ascii")
                payload_lines.append(f"# Array: {name}\n")
                payload_lines.append(f"{name}_b64 = '{b64}'\n")
                payload_lines.append(
                    f"{name} = np.load(io.BytesIO(base64.b64decode({name}_b64)))\n"
                )

        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": payload_lines,
        })

    # Cell 5: User Code
    code_lines = [line + "\n" for line in code.strip().splitlines()]
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": code_lines,
    })

    # Cell 6: Completion & Results Export
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Execution finished successfully.\n",
            "print('Task finished successfully on Colab cloud.')\n",
        ],
    })

    nb = {
        "nbformat": 4,
        "nbformat_minor": 0,
        "metadata": {
            "colab": {
                "name": title,
                "provenance": [],
            },
            "kernelspec": {
                "name": "python3",
                "display_name": "Python 3",
            },
            "language_info": {
                "name": "python",
            },
        },
        "cells": cells,
    }

    if save_path:
        p = Path(save_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(nb, indent=2), encoding="utf-8")

    return nb


__all__ = ["colab_auth_guide", "generate_colab_notebook"]
