"""Discrete Choice Endogenous Grid Method (DC-EGM) & Upper Envelope Filtering.

Implements the Discrete Choice Endogenous Grid Method of Iskhakov, Jørgensen,
Rust & Schjerning (2017) for dynamic economic models with continuous
consumption/saving choices and discrete choices (e.g., retirement, labor force
participation, default).

Key Components:
1. `upper_envelope`: Fast upper envelope algorithm filtering non-monotonic
   and sub-optimal branches of the endogenous grid generated by non-convex
   value functions, detecting crossing points and interpolating onto target grids.
2. `DCEGMProblem`: Frozen dataclass defining discrete-continuous dynamic programs,
   supporting Extreme Value Type I taste shocks (logit choice probabilities),
   envelope-theorem marginal value calculations without numerical differentiation,
   deterministic choice limits (sigma_eps -> 0), and multi-backend acceleration.
3. `DCEGMSolution`: Frozen dataclass containing continuous choice policies,
   values, choice probabilities, integrated value, and presentation methods
   (.summary(), .plot(), .to_frame(), .to_markdown(), .to_latex(), .to_typst()).
4. `solve_dcegm`: Functional entry point for solving discrete-continuous problems.
"""
from __future__ import annotations

import time
import warnings
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Union

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from puremacro import _backend as _bk
from puremacro.reports import _df_to_latex, _df_to_markdown, _df_to_typst


# ---------------------------------------------------------------------------
# ChoiceMapping Container: dict subclass with NumPy array interoperability
# ---------------------------------------------------------------------------

class ChoiceMapping(dict):
    """Dictionary of choice arrays supporting numpy array operations and elementwise comparisons."""

    def __array__(self, dtype: Any = None) -> np.ndarray:
        keys = sorted(self.keys())
        return np.array([self[k] for k in keys], dtype=dtype)

    def __ge__(self, other: Any) -> np.ndarray:
        return self.__array__() >= other

    def __le__(self, other: Any) -> np.ndarray:
        return self.__array__() <= other

    def __gt__(self, other: Any) -> np.ndarray:
        return self.__array__() > other

    def __lt__(self, other: Any) -> np.ndarray:
        return self.__array__() < other

    @property
    def shape(self) -> Tuple[int, ...]:
        return self.__array__().shape

    @property
    def ndim(self) -> int:
        return self.__array__().ndim

    def min(self, *args: Any, **kwargs: Any) -> Any:
        return self.__array__().min(*args, **kwargs)

    def max(self, *args: Any, **kwargs: Any) -> Any:
        return self.__array__().max(*args, **kwargs)


# ---------------------------------------------------------------------------
# Numba JIT Accelerable Kernels
# ---------------------------------------------------------------------------

@_bk.njit_fallback(fastmath=True)
def _logsumexp_probs_1d_kernel(v: np.ndarray, sigma_eps: float) -> Tuple[float, np.ndarray]:
    """Compute log-sum-exp inclusive value and multinomial logit probabilities."""
    n = len(v)
    v_max = -1e300
    for i in range(n):
        if v[i] > v_max:
            v_max = v[i]

    if sigma_eps <= 1e-12:
        # Deterministic choice limit
        ties = 0
        for i in range(n):
            if abs(v[i] - v_max) < 1e-12:
                ties += 1
        probs = np.zeros(n, dtype=np.float64)
        for i in range(n):
            if abs(v[i] - v_max) < 1e-12:
                probs[i] = 1.0 / float(ties)
        return v_max, probs

    sum_exp = 0.0
    probs = np.zeros(n, dtype=np.float64)
    for i in range(n):
        val = np.exp((v[i] - v_max) / sigma_eps)
        probs[i] = val
        sum_exp += val

    v_inc = v_max + sigma_eps * np.log(sum_exp)
    for i in range(n):
        probs[i] /= sum_exp

    return v_inc, probs


@_bk.njit_fallback(fastmath=True)
def _logsumexp_probs_2d_kernel(
    v_mat: np.ndarray, sigma_eps: float
) -> Tuple[np.ndarray, np.ndarray]:
    """Compute log-sum-exp and choice probabilities across discrete choices (axis 0)."""
    n_d, n_m = v_mat.shape
    v_inc = np.zeros(n_m, dtype=np.float64)
    probs = np.zeros((n_d, n_m), dtype=np.float64)

    for m in range(n_m):
        v_col = v_mat[:, m]
        v_max = -1e300
        for d in range(n_d):
            if v_col[d] > v_max:
                v_max = v_col[d]

        if sigma_eps <= 1e-12:
            ties = 0
            for d in range(n_d):
                if abs(v_col[d] - v_max) < 1e-12:
                    ties += 1
            for d in range(n_d):
                if abs(v_col[d] - v_max) < 1e-12:
                    probs[d, m] = 1.0 / float(ties)
                else:
                    probs[d, m] = 0.0
            v_inc[m] = v_max
        else:
            sum_exp = 0.0
            for d in range(n_d):
                val = np.exp((v_col[d] - v_max) / sigma_eps)
                probs[d, m] = val
                sum_exp += val
            v_inc[m] = v_max + sigma_eps * np.log(sum_exp)
            for d in range(n_d):
                probs[d, m] /= sum_exp

    return v_inc, probs


# ---------------------------------------------------------------------------
# UpperEnvelopeResult Container
# ---------------------------------------------------------------------------

class UpperEnvelopeResult(tuple):
    """Result of upper envelope filtering, unpackable as (policy, value)."""

    def __new__(
        cls,
        policy: np.ndarray,
        value: np.ndarray,
        grid: Optional[np.ndarray] = None,
    ):
        return super().__new__(cls, (policy, value))

    def __init__(
        self,
        policy: np.ndarray,
        value: np.ndarray,
        grid: Optional[np.ndarray] = None,
    ):
        self._policy = policy
        self._value = value
        self._grid = grid

    @property
    def policy(self) -> np.ndarray:
        """Filtered continuous choice policy on target exogenous grid."""
        return self._policy

    @property
    def value(self) -> np.ndarray:
        """Filtered value function on target exogenous grid."""
        return self._value

    @property
    def grid(self) -> Optional[np.ndarray]:
        """Target exogenous evaluation grid."""
        return self._grid

    @property
    def exog_grid(self) -> Optional[np.ndarray]:
        """Alias for target exogenous evaluation grid."""
        return self._grid

    @property
    def aprime(self) -> Optional[np.ndarray]:
        """Implied next-period asset policy a' = M - c."""
        if self._grid is not None:
            return np.maximum(self._grid - self._policy, 0.0)
        return None

    def __repr__(self) -> str:
        grid_len = len(self._grid) if self._grid is not None else len(self._policy)
        return f"UpperEnvelopeResult(points={grid_len}, policy_range=[{self._policy.min():.4g}, {self._policy.max():.4g}])"


# ---------------------------------------------------------------------------
# Upper Envelope Algorithm
# ---------------------------------------------------------------------------

def upper_envelope(
    endog_grid: Sequence[float] | np.ndarray,
    policy: Sequence[float] | np.ndarray,
    value: Sequence[float] | np.ndarray,
    exog_grid: Sequence[float] | np.ndarray,
    a_min: Optional[float] = None,
    v_cont_amin: Optional[float] = None,
    u_fn: Optional[Callable[[Union[float, np.ndarray]], Union[float, np.ndarray]]] = None,
    **kwargs: Any,
) -> UpperEnvelopeResult:
    r"""Upper Envelope algorithm filtering non-monotonic and sub-optimal branches.

    Evaluates the endogenous grid M(a') = a' + c(a'). Non-convexities in the
    continuation value induce non-monotonic folds where \partial M / \partial a' < 0.
    This algorithm partitions the raw endogenous points into strictly increasing
    segments, eliminates dominated / falling branches (local minima), compares
    competing branches in overlapping regions, and interpolates the optimal
    upper envelope onto `exog_grid`.

    Parameters
    ----------
    endog_grid : Sequence[float] | np.ndarray
        Raw endogenous cash-on-hand grid points M(a').
    policy : Sequence[float] | np.ndarray
        Raw choice policy (e.g. consumption c(a')).
    value : Sequence[float] | np.ndarray
        Raw choice value function v(a').
    exog_grid : Sequence[float] | np.ndarray
        Regular target exogenous evaluation grid for cash-on-hand M.
    a_min : float, optional
        Borrowing constraint lower bound on assets.
    v_cont_amin : float, optional
        Continuation value at borrowing limit a' = a_min.
    u_fn : Callable, optional
        Utility function for constrained region extrapolation.

    Returns
    -------
    UpperEnvelopeResult
        Tuple-like container unpackable as (c_filtered, v_filtered) with
        attributes .policy, .value, and .grid.
    """
    m_raw = np.asarray(endog_grid, dtype=np.float64)
    c_raw = np.asarray(policy, dtype=np.float64)
    v_raw = np.asarray(value, dtype=np.float64)
    exog = np.asarray(exog_grid, dtype=np.float64)

    n_raw = len(m_raw)
    if n_raw == 0:
        raise ValueError("endog_grid must not be empty.")
    if len(c_raw) != n_raw or len(v_raw) != n_raw:
        raise ValueError(
            f"Dimension mismatch: endog_grid ({n_raw}), policy ({len(c_raw)}), value ({len(v_raw)})."
        )
    if len(exog) == 0:
        raise ValueError("exog_grid must not be empty.")

    # 1. Identify continuous rising segments where M is strictly increasing
    # Each entry is (m_seg, c_seg, v_seg, is_constrained)
    segments: List[Tuple[np.ndarray, np.ndarray, np.ndarray, bool]] = []
    i = 0
    while i < n_raw:
        start = i
        while i < n_raw - 1 and m_raw[i + 1] >= m_raw[i]:
            i += 1
        end = i + 1
        if end - start >= 2:
            segments.append((m_raw[start:end], c_raw[start:end], v_raw[start:end], False))
        elif end - start == 1 and not segments:
            # Single-point fallback
            segments.append((m_raw[start:end], c_raw[start:end], v_raw[start:end], False))
        i = end
        # Skip over the falling branch (local minima violating second-order conditions)
        while i < n_raw - 1 and m_raw[i + 1] < m_raw[i]:
            i += 1
        i += 1

    if not segments:
        # Monotonic sorting fallback if no segmented pattern detected
        order = np.argsort(m_raw)
        segments.append((m_raw[order], c_raw[order], v_raw[order], False))

    # 2. Add constrained segment if cash-on-hand extends below lowest unconstrained M
    m_min_unconstrained = min(s[0][0] for s in segments)
    if a_min is not None and m_min_unconstrained > a_min:
        m_con = np.linspace(a_min, m_min_unconstrained, num=30)
        c_con = np.maximum(m_con - a_min, 1e-6)
        if u_fn is not None and v_cont_amin is not None:
            v_con = u_fn(c_con) + v_cont_amin
        else:
            slope_v = max((segments[0][2][1] - segments[0][2][0]) / max(segments[0][0][1] - segments[0][0][0], 1e-8), 0.1)
            v_con = segments[0][2][0] + slope_v * (m_con - m_min_unconstrained)
        segments.insert(0, (m_con, c_con, v_con, True))

    # 3. Evaluate each segment on the target exogenous grid
    v_candidates: List[np.ndarray] = []
    c_candidates: List[np.ndarray] = []
    m_min_global = min(s[0][0] for s in segments)

    for m_seg, c_seg, v_seg, is_con in segments:
        v_eval = np.interp(exog, m_seg, v_seg, left=-np.inf, right=-np.inf)
        c_eval = np.interp(exog, m_seg, c_seg, left=0.0, right=0.0)

        # Left extrapolation for lowest segment
        left_mask = exog < m_seg[0]
        if np.any(left_mask) and m_seg[0] <= m_min_global + 1e-5:
            denom = max(m_seg[1] - m_seg[0], 1e-8)
            slope_c = max((c_seg[1] - c_seg[0]) / denom, 0.1)
            slope_v = max((v_seg[1] - v_seg[0]) / denom, 0.1)
            c_eval[left_mask] = np.maximum(c_seg[0] + slope_c * (exog[left_mask] - m_seg[0]), 1e-6)
            v_eval[left_mask] = v_seg[0] + slope_v * (exog[left_mask] - m_seg[0])

        # Right extension: ONLY for unconstrained segments!
        # (A borrowing-constrained segment terminates at unconstrained threshold)
        if not is_con:
            right_mask = exog > m_seg[-1]
            if np.any(right_mask):
                denom = max(m_seg[-1] - m_seg[-2], 1e-8)
                slope_v = max((v_seg[-1] - v_seg[-2]) / denom, 1e-4)
                c_eval[right_mask] = c_seg[-1] + (exog[right_mask] - m_seg[-1])
                v_eval[right_mask] = v_seg[-1] + slope_v * (exog[right_mask] - m_seg[-1])

        v_candidates.append(v_eval)
        c_candidates.append(c_eval)

    v_mat = np.column_stack(v_candidates)
    c_mat = np.column_stack(c_candidates)

    # 4. Pointwise upper envelope maximum
    best_seg = np.argmax(v_mat, axis=1)
    v_clean = np.choose(best_seg, v_mat.T)
    c_clean = np.choose(best_seg, c_mat.T)

    # By free disposal / monotonicity of value functions, V(M) is non-decreasing
    v_clean = np.maximum.accumulate(v_clean)
    c_clean = np.maximum(c_clean, 1e-6)

    return UpperEnvelopeResult(c_clean, v_clean, exog)


# ---------------------------------------------------------------------------
# DCEGMSolution Container
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class DCEGMSolution:
    """Solution container for discrete-continuous models solved via DC-EGM.

    Parameters
    ----------
    asset_grid : np.ndarray
        Exogenous evaluation grid of cash-on-hand M.
    choice_policies : dict[int, np.ndarray] | ChoiceMapping
        Mapping from discrete choice d to continuous consumption policy c_d(M).
    choice_values : dict[int, np.ndarray] | ChoiceMapping
        Mapping from discrete choice d to conditional value function v_d(M).
    choice_probabilities : dict[int, np.ndarray] | ChoiceMapping
        Mapping from discrete choice d to conditional choice probability P(d | M).
    integrated_value : np.ndarray
        Inclusive integrated value function V(M) under taste shocks.
    converged : bool
        Whether the recursive dynamic programming algorithm converged.
    metadata : dict[str, Any]
        Solver diagnostics, iterations, tolerances, and execution metadata.
    """

    asset_grid: np.ndarray
    choice_policies: Dict[int, np.ndarray]
    choice_values: Dict[int, np.ndarray]
    choice_probabilities: Dict[int, np.ndarray]
    integrated_value: np.ndarray
    converged: bool
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def m_grid(self) -> np.ndarray:
        """Cash-on-hand evaluation grid."""
        return self.asset_grid

    @property
    def c(self) -> np.ndarray:
        """Array of consumption policies across choices, shape (n_choices, n_m)."""
        return np.array([self.choice_policies[d] for d in sorted(self.choice_policies.keys())])

    @property
    def v(self) -> np.ndarray:
        """Array of conditional values across choices, shape (n_choices, n_m)."""
        return np.array([self.choice_values[d] for d in sorted(self.choice_values.keys())])

    @property
    def probabilities(self) -> np.ndarray:
        """Array of choice probabilities, shape (n_choices, n_m)."""
        return np.array([self.choice_probabilities[d] for d in sorted(self.choice_probabilities.keys())])

    @property
    def probs(self) -> np.ndarray:
        """Alias for probabilities."""
        return self.probabilities

    @property
    def P(self) -> np.ndarray:
        """Alias for probabilities array."""
        return self.probabilities

    @property
    def aprime(self) -> Dict[int, np.ndarray]:
        """Next-period saving policies a' = M - c_d(M) for each choice d."""
        a_min = self.metadata.get("a_min", 0.0)
        return {
            d: np.maximum(self.asset_grid - self.choice_policies[d], a_min)
            for d in self.choice_policies
        }

    @property
    def n_iter(self) -> int:
        """Number of iterations performed."""
        return int(self.metadata.get("n_iter", 0))

    @property
    def sup_norm(self) -> float:
        """Final sup-norm error."""
        return float(self.metadata.get("sup_norm", 0.0))

    @property
    def backend(self) -> str:
        """Executed numerical backend."""
        return str(self.metadata.get("backend", "numpy"))

    @property
    def sigma_eps(self) -> float:
        """Scale parameter of taste shocks."""
        return float(self.metadata.get("sigma_eps", 0.0))

    def policy(
        self, s: Union[float, Sequence[float], np.ndarray], choice: Optional[int] = None
    ) -> Union[float, np.ndarray]:
        """Evaluate continuous consumption policy at arbitrary cash-on-hand state(s).

        Parameters
        ----------
        s : float | Sequence[float] | np.ndarray
            Cash-on-hand query points.
        choice : int, optional
            Discrete choice index d. If None, computes expected policy E[c(s)] = sum_d P(d|s) c_d(s).

        Returns
        -------
        float | np.ndarray
            Interpolated continuous policy values.
        """
        s_arr = np.asarray(s, dtype=np.float64)
        is_scalar = s_arr.ndim == 0

        if choice is not None:
            if choice not in self.choice_policies:
                raise ValueError(f"Invalid choice {choice}; choices: {list(self.choice_policies.keys())}")
            c_vals = np.interp(s_arr, self.asset_grid, self.choice_policies[choice])
            return float(c_vals) if is_scalar else c_vals

        # Expected policy across discrete choices
        c_exp = np.zeros_like(s_arr)
        for d in self.choice_policies:
            c_d = np.interp(s_arr, self.asset_grid, self.choice_policies[d])
            p_d = np.interp(s_arr, self.asset_grid, self.choice_probabilities[d])
            c_exp += p_d * c_d
        return float(c_exp) if is_scalar else c_exp

    def value(
        self, s: Union[float, Sequence[float], np.ndarray], choice: Optional[int] = None
    ) -> Union[float, np.ndarray]:
        """Evaluate value function at arbitrary cash-on-hand state(s).

        Parameters
        ----------
        s : float | Sequence[float] | np.ndarray
            Cash-on-hand query points.
        choice : int, optional
            Discrete choice index d. If None, evaluates inclusive integrated value V(s).

        Returns
        -------
        float | np.ndarray
            Interpolated continuous value(s).
        """
        s_arr = np.asarray(s, dtype=np.float64)
        is_scalar = s_arr.ndim == 0

        if choice is not None:
            if choice not in self.choice_values:
                raise ValueError(f"Invalid choice {choice}; choices: {list(self.choice_values.keys())}")
            v_vals = np.interp(s_arr, self.asset_grid, self.choice_values[choice])
            return float(v_vals) if is_scalar else v_vals

        v_inc = np.interp(s_arr, self.asset_grid, self.integrated_value)
        return float(v_inc) if is_scalar else v_inc

    def choice_prob(
        self, s: Union[float, Sequence[float], np.ndarray], choice: Optional[int] = None
    ) -> Union[float, np.ndarray]:
        """Evaluate discrete choice probabilities at arbitrary cash-on-hand state(s).

        Parameters
        ----------
        s : float | Sequence[float] | np.ndarray
            Cash-on-hand query points.
        choice : int, optional
            Discrete choice index d. If None, returns array of shape (n_choices, ...)
            with probabilities for all choices.

        Returns
        -------
        float | np.ndarray
            Interpolated choice probability values.
        """
        s_arr = np.asarray(s, dtype=np.float64)
        is_scalar = s_arr.ndim == 0

        if choice is not None:
            if choice not in self.choice_probabilities:
                raise ValueError(f"Invalid choice {choice}; choices: {list(self.choice_probabilities.keys())}")
            p_vals = np.interp(s_arr, self.asset_grid, self.choice_probabilities[choice])
            return float(p_vals) if is_scalar else p_vals

        all_probs = [
            np.interp(s_arr, self.asset_grid, self.choice_probabilities[d])
            for d in sorted(self.choice_probabilities.keys())
        ]
        res = np.array(all_probs)
        return res[:, 0] if (is_scalar and res.ndim > 1) else res

    def choice_probability(
        self, s: Union[float, Sequence[float], np.ndarray], choice: Optional[int] = None
    ) -> Union[float, np.ndarray]:
        """Alias for choice_prob."""
        return self.choice_prob(s, choice=choice)

    def summary(self) -> pd.DataFrame:
        """Structured summary DataFrame of DC-EGM solver results."""
        n_choices = len(self.choice_policies)
        elapsed = self.metadata.get("elapsed_time", np.nan)
        a_min = self.metadata.get("a_min", 0.0)
        beta = self.metadata.get("beta", np.nan)
        r = self.metadata.get("r", np.nan)

        rows = [
            {"Metric": "Method", "Value": "Discrete Choice EGM (DC-EGM)"},
            {"Metric": "Discrete Choices (D)", "Value": str(n_choices)},
            {"Metric": "Evaluation Grid Points (M)", "Value": str(len(self.asset_grid))},
            {"Metric": "Cash-on-Hand Range", "Value": f"[{self.asset_grid[0]:.4g}, {self.asset_grid[-1]:.4g}]"},
            {"Metric": "Taste Shock Scale (sigma_eps)", "Value": f"{self.sigma_eps:.4g}"},
            {"Metric": "Borrowing Limit (a_min)", "Value": f"{a_min:.4g}"},
            {"Metric": "Discount Factor (beta)", "Value": f"{beta:.4g}" if np.isfinite(beta) else "N/A"},
            {"Metric": "Interest Rate (r)", "Value": f"{r:.4g}" if np.isfinite(r) else "N/A"},
            {"Metric": "Converged", "Value": str(self.converged)},
            {"Metric": "Iterations", "Value": str(self.n_iter)},
            {"Metric": "Sup Norm", "Value": f"{self.sup_norm:.4e}"},
            {"Metric": "Backend", "Value": str(self.backend)},
            {"Metric": "Elapsed Time (s)", "Value": f"{elapsed:.4f}" if np.isfinite(elapsed) else "N/A"},
        ]
        return pd.DataFrame(rows).set_index("Metric")

    def to_frame(self) -> pd.DataFrame:
        """Return tabulations of policies, values, and probabilities on the grid."""
        df = pd.DataFrame({"M": self.asset_grid})
        for d in sorted(self.choice_policies.keys()):
            df[f"c_{d}"] = self.choice_policies[d]
            df[f"v_{d}"] = self.choice_values[d]
            df[f"prob_{d}"] = self.choice_probabilities[d]
        df["V_integrated"] = self.integrated_value
        return df

    def to_markdown(self, **kwargs: Any) -> str:
        """Render summary table as Markdown."""
        return _df_to_markdown(self.summary(), **kwargs)

    def to_latex(self, **kwargs: Any) -> str:
        """Render summary table as LaTeX tabular."""
        return _df_to_latex(self.summary(), **kwargs)

    def to_typst(self, **kwargs: Any) -> str:
        """Render summary table as Typst table."""
        return _df_to_typst(self.summary(), **kwargs)

    def plot(
        self, figsize: Tuple[float, float] = (12, 8), show: bool = False
    ) -> plt.Figure:
        """Plot diagnostic 4-panel figure of policies, values, and probabilities.

        Returns
        -------
        matplotlib.figure.Figure
            Figure instance containing the diagnostic subplots.
        """
        fig, axes = plt.subplots(2, 2, figsize=figsize, constrained_layout=True)
        colors = ["tab:blue", "tab:orange", "tab:green", "tab:red", "tab:purple", "tab:brown"]

        # Panel 1: Consumption Policies
        ax1 = axes[0, 0]
        for d, col in zip(sorted(self.choice_policies.keys()), colors):
            ax1.plot(self.asset_grid, self.choice_policies[d], lw=2, color=col, label=f"$c_{d}(M)$")
        c_exp = self.policy(self.asset_grid, choice=None)
        ax1.plot(self.asset_grid, c_exp, color="black", ls="--", lw=1.5, label="$E[c(M)]$")
        ax1.set_title("Consumption Policies")
        ax1.set_xlabel("Cash on Hand $M$")
        ax1.set_ylabel("Consumption $c$")
        ax1.legend(loc="best", frameon=True)
        ax1.grid(True, alpha=0.3)

        # Panel 2: Saving Policies
        ax2 = axes[0, 1]
        for d, col in zip(sorted(self.choice_policies.keys()), colors):
            a_prime_d = np.maximum(self.asset_grid - self.choice_policies[d], self.metadata.get("a_min", 0.0))
            ax2.plot(self.asset_grid, a_prime_d, lw=2, color=col, label=f"$a'_{d}(M)$")
        ax2.plot(self.asset_grid, self.asset_grid, color="gray", ls=":", alpha=0.7, label="$a'=M$")
        ax2.set_title("Next-Period Asset Policies $a' = M - c$")
        ax2.set_xlabel("Cash on Hand $M$")
        ax2.set_ylabel("Next Assets $a'$")
        ax2.legend(loc="best", frameon=True)
        ax2.grid(True, alpha=0.3)

        # Panel 3: Value Functions
        ax3 = axes[1, 0]
        for d, col in zip(sorted(self.choice_values.keys()), colors):
            ax3.plot(self.asset_grid, self.choice_values[d], lw=2, color=col, label=f"$v_{d}(M)$")
        ax3.plot(self.asset_grid, self.integrated_value, color="black", ls="--", lw=1.5, label="$V(M)$")
        ax3.set_title("Value Functions")
        ax3.set_xlabel("Cash on Hand $M$")
        ax3.set_ylabel("Value $V$")
        ax3.legend(loc="best", frameon=True)
        ax3.grid(True, alpha=0.3)

        # Panel 4: Choice Probabilities
        ax4 = axes[1, 1]
        for d, col in zip(sorted(self.choice_probabilities.keys()), colors):
            ax4.plot(self.asset_grid, self.choice_probabilities[d], lw=2, color=col, label=f"$P(d={d} \\mid M)$")
        ax4.set_title("Discrete Choice Probabilities")
        ax4.set_xlabel("Cash on Hand $M$")
        ax4.set_ylabel("Probability $P(d \\mid M)$")
        ax4.set_ylim(-0.05, 1.05)
        ax4.legend(loc="best", frameon=True)
        ax4.grid(True, alpha=0.3)

        if show:
            plt.show()
        return fig


# ---------------------------------------------------------------------------
# DCEGMProblem Class
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class DCEGMProblem:
    """Discrete Choice Endogenous Grid Method Problem.

    Parameters
    ----------
    a_grid : Sequence[float] | np.ndarray
        Exogenous grid of post-decision savings a' >= a_min.
    m_grid : Sequence[float] | np.ndarray | None, default None
        Exogenous target evaluation grid of cash-on-hand M. If None, constructed
        automatically spanning the feasible cash-on-hand range.
    n_choices : int, default 2
        Number of discrete choices d in {0, 1, ..., n_choices - 1}.
    u_fn : Callable[[np.ndarray, int], np.ndarray] | Sequence[Callable] | None, optional
        Utility function u(c, d). Default log utility with retirement disutility.
    u_prime : Callable[[np.ndarray, int], np.ndarray] | Sequence[Callable] | None, optional
        Marginal utility function u'(c, d). Default 1/c.
    u_prime_inv : Callable[[np.ndarray, int], np.ndarray] | Sequence[Callable] | None, optional
        Inverse marginal utility (u')^{-1}(w, d). Default 1/w.
    beta : float, default 0.96
        Discount factor beta in (0, 1).
    r : float, default 0.04
        Real interest rate r > -1 (gross rate R = 1 + r).
    income : Any, optional
        Income specification y(d) or y(d, z). Default [1.0, 0.4].
    P_z : np.ndarray, optional
        Markov transition matrix for shock z, shape (n_z, n_z). Default [[1.0]].
    z_grid : Sequence[float] | np.ndarray, optional
        Exogenous shock grid of length n_z. Default [1.0].
    sigma_eps : float, default 0.2
        Scale parameter of Extreme Value Type I taste shocks (sigma_eps >= 0).
    a_min : float, default 0.0
        Borrowing constraint lower bound on assets.
    horizon : int | None, default None
        Finite horizon periods T (if specified) or None for infinite horizon.
    discrete_transitions : np.ndarray | None, default None
        Feasibility transition matrix T(d' | d) across discrete choices.
    options : dict[str, Any] | None, default None
        Solver options: tol (default 1e-5), max_iter (default 1000).
    metadata : dict[str, Any] | None, default None
        User metadata.
    """

    a_grid: Sequence[float] | np.ndarray
    m_grid: Optional[Sequence[float] | np.ndarray] = None
    n_choices: int = 2
    u_fn: Optional[Any] = None
    u_prime: Optional[Any] = None
    u_prime_inv: Optional[Any] = None
    beta: float = 0.96
    r: float = 0.04
    income: Optional[Any] = None
    P_z: Optional[np.ndarray] = None
    z_grid: Optional[Sequence[float] | np.ndarray] = None
    sigma_eps: float = 0.2
    a_min: float = 0.0
    horizon: Optional[int] = None
    discrete_transitions: Optional[np.ndarray] = None
    options: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None

    def __post_init__(self) -> None:
        a_arr = np.asarray(self.a_grid, dtype=np.float64)

        if len(a_arr) < 2:
            raise ValueError("a_grid must have at least 2 points.")
        if np.any(np.diff(a_arr) <= 0):
            raise ValueError("a_grid must be strictly increasing.")
        if not (0.0 < self.beta < 1.0):
            raise ValueError(f"beta must be in (0, 1); got {self.beta}")
        if self.r <= -1.0:
            raise ValueError(f"r must be > -1; got {self.r}")
        if self.sigma_eps < 0.0:
            raise ValueError(f"sigma_eps must be >= 0; got {self.sigma_eps}")
        if self.n_choices < 2:
            raise ValueError(f"n_choices must be >= 2; got {self.n_choices}")

        if self.discrete_transitions is None:
            if self.n_choices == 2:
                # Canonical Iskhakov et al. (2017) retirement choice: retirement is absorbing
                object.__setattr__(
                    self, "discrete_transitions", np.array([[1.0, 1.0], [0.0, 1.0]], dtype=np.float64)
                )
            else:
                object.__setattr__(
                    self, "discrete_transitions", np.ones((self.n_choices, self.n_choices), dtype=np.float64)
                )

        if self.m_grid is None:
            # Construct default cash-on-hand grid spanning feasible range
            m_min = max(a_arr[0], self.a_min) + 1e-4
            m_max = max(1.25 * a_arr[-1] + 2.0, a_arr[-1] + 1.0)
            n_m = max(len(a_arr), 60)
            m_def = np.linspace(m_min, m_max, num=n_m)
            object.__setattr__(self, "m_grid", m_def)
        else:
            m_arr = np.asarray(self.m_grid, dtype=np.float64)
            if len(m_arr) < 2:
                raise ValueError("m_grid must have at least 2 points.")
            if np.any(np.diff(m_arr) <= 0):
                raise ValueError("m_grid must be strictly increasing.")
            object.__setattr__(self, "m_grid", m_arr)

    def _eval_u(self, c: np.ndarray, d: int) -> np.ndarray:
        """Evaluate utility u(c, d)."""
        if self.u_fn is not None:
            if callable(self.u_fn):
                return np.asarray(self.u_fn(c, d), dtype=np.float64)
            if isinstance(self.u_fn, (list, tuple)):
                return np.asarray(self.u_fn[d](c), dtype=np.float64)
        # Canonical default: log utility with retirement disutility of work (0.5 for d=0)
        c_safe = np.maximum(c, 1e-10)
        util = np.log(c_safe)
        if d == 0:
            util -= 0.5
        return util

    def _eval_u_prime(self, c: np.ndarray, d: int) -> np.ndarray:
        """Evaluate marginal utility u'(c, d)."""
        if self.u_prime is not None:
            if callable(self.u_prime):
                return np.asarray(self.u_prime(c, d), dtype=np.float64)
            if isinstance(self.u_prime, (list, tuple)):
                return np.asarray(self.u_prime[d](c), dtype=np.float64)
        c_safe = np.maximum(c, 1e-10)
        return 1.0 / c_safe

    def _eval_u_prime_inv(self, w: np.ndarray, d: int) -> np.ndarray:
        """Evaluate inverse marginal utility (u')^{-1}(w, d)."""
        if self.u_prime_inv is not None:
            if callable(self.u_prime_inv):
                return np.asarray(self.u_prime_inv(w, d), dtype=np.float64)
            if isinstance(self.u_prime_inv, (list, tuple)):
                return np.asarray(self.u_prime_inv[d](w), dtype=np.float64)
        w_safe = np.maximum(w, 1e-10)
        return 1.0 / w_safe

    def _get_income(self, d: int, zi: int = 0) -> float:
        """Retrieve income y(d, z)."""
        if self.income is None:
            # Default retirement model: y(0)=1.0, y(1)=0.4
            return 1.0 if d == 0 else 0.4
        if callable(self.income):
            try:
                return float(self.income(d, zi))
            except TypeError:
                return float(self.income(d))
        inc_arr = np.asarray(self.income, dtype=np.float64)
        if inc_arr.ndim == 1:
            return float(inc_arr[d])
        if inc_arr.ndim == 2:
            return float(inc_arr[d, zi])
        return float(inc_arr)

    def solve(self, backend: str = "numpy", **kwargs: Any) -> DCEGMSolution:
        """Solve the DC-EGM problem.

        Parameters
        ----------
        backend : str, default "numpy"
            Compute backend: "numpy", "numba", "mlx", or "cupy".
            Automatically falls back to "numpy" if requested accelerator is absent.
        **kwargs : Any
            Overrides for options (tol, max_iter).

        Returns
        -------
        DCEGMSolution
            Solved policy functions, conditional value functions, choice
            probabilities, integrated value, and presentation interface.
        """
        t0 = time.perf_counter()
        b = str(backend).strip().lower()

        if b not in _bk.SUPPORTED:
            raise ValueError(f"Unknown backend {backend!r}; supported: {_bk.SUPPORTED}")

        resolved_backend = b
        if not _bk.backend_available(b):
            warnings.warn(
                f"Backend {backend!r} requested but not available; falling back to 'numpy'.",
                UserWarning,
                stacklevel=2,
            )
            resolved_backend = "numpy"

        # Solver options
        opts = dict(self.options or {})
        opts.update(kwargs)
        tol = float(opts.get("tol", 1e-5))
        max_iter = int(opts.get("max_iter", 1000))

        a_grid = np.asarray(self.a_grid, dtype=np.float64)
        m_grid = np.asarray(self.m_grid, dtype=np.float64)
        n_a = len(a_grid)
        n_m = len(m_grid)
        n_d = self.n_choices
        R = 1.0 + self.r
        beta = self.beta
        sigma_eps = self.sigma_eps

        # Exogenous shocks
        P_z = np.asarray(self.P_z, dtype=np.float64) if self.P_z is not None else np.array([[1.0]])
        n_z = P_z.shape[0]

        # Discrete transitions T(d' | d): default all allowed
        if self.discrete_transitions is not None:
            T_d = np.asarray(self.discrete_transitions, dtype=np.float64)
        else:
            T_d = np.ones((n_d, n_d), dtype=np.float64)

        # Initialize terminal or initial guess
        # Shape: (n_d, n_m, n_z)
        c_curr = np.zeros((n_d, n_m, n_z), dtype=np.float64)
        v_curr = np.zeros((n_d, n_m, n_z), dtype=np.float64)

        for d in range(n_d):
            for zi in range(n_z):
                c_curr[d, :, zi] = np.maximum(m_grid - self.a_min, 1e-4)
                v_curr[d, :, zi] = self._eval_u(c_curr[d, :, zi], d)

        # Inclusive value initial
        v_inc_curr = np.zeros((n_m, n_z), dtype=np.float64)
        probs_curr = np.zeros((n_d, n_m, n_z), dtype=np.float64)
        for zi in range(n_z):
            v_inc_curr[:, zi], probs_curr[:, :, zi] = _logsumexp_probs_2d_kernel(
                v_curr[:, :, zi], sigma_eps
            )

        converged = False
        n_iter = 0
        sup_norm = np.inf

        is_finite = self.horizon is not None
        steps = self.horizon if is_finite else max_iter

        for it in range(1, steps + 1):
            n_iter = it
            c_next = c_curr.copy()
            v_next = v_curr.copy()
            c_new = np.zeros((n_d, n_m, n_z), dtype=np.float64)
            v_new = np.zeros((n_d, n_m, n_z), dtype=np.float64)

            for d in range(n_d):
                for zi in range(n_z):
                    # Next-period cash-on-hand for each feasible future choice d' and shock z'
                    # Compute expected continuation value and marginal value
                    w_cont = np.zeros(n_a, dtype=np.float64)
                    v_cont = np.zeros(n_a, dtype=np.float64)

                    for zj in range(n_z):
                        prob_z = P_z[zi, zj]
                        if prob_z <= 1e-12:
                            continue

                        # Future choice values and marginal values on next asset grid
                        v_fut = np.zeros((n_d, n_a), dtype=np.float64)
                        c_fut = np.zeros((n_d, n_a), dtype=np.float64)

                        for d_prime in range(n_d):
                            if T_d[d, d_prime] <= 1e-12:
                                v_fut[d_prime] = -1e300
                                c_fut[d_prime] = 1e-4
                                continue

                            M_prime = R * a_grid + self._get_income(d_prime, zj)
                            v_fut[d_prime] = np.interp(M_prime, m_grid, v_next[d_prime, :, zj])
                            c_fut[d_prime] = np.maximum(
                                np.interp(M_prime, m_grid, c_next[d_prime, :, zj]), 1e-4
                            )

                        # Inclusive value and choice probabilities for tomorrow
                        v_inc_prime, p_prime = _logsumexp_probs_2d_kernel(v_fut, sigma_eps)

                        # Envelope theorem expected marginal value of wealth without numerical diff!
                        # V'(M') = sum_{d'} P(d' | M') u'(c_{d'}(M'), d')
                        dV_prime = np.zeros(n_a, dtype=np.float64)
                        for d_prime in range(n_d):
                            if T_d[d, d_prime] > 1e-12:
                                u_p = self._eval_u_prime(c_fut[d_prime], d_prime)
                                dV_prime += p_prime[d_prime] * u_p

                        w_cont += prob_z * (beta * R * dV_prime)
                        v_cont += prob_z * (beta * v_inc_prime)

                    # Invert Euler equation: c = (u')^{-1}(w)
                    c_endog = self._eval_u_prime_inv(w_cont, d)
                    m_endog = a_grid + c_endog
                    v_endog = self._eval_u(c_endog, d) + v_cont

                    # Upper envelope filtering
                    v_amin = float(v_cont[0])
                    res_ue = upper_envelope(
                        m_endog,
                        c_endog,
                        v_endog,
                        m_grid,
                        a_min=self.a_min,
                        v_cont_amin=v_amin,
                        u_fn=lambda c_: self._eval_u(c_, d),
                    )
                    c_new[d, :, zi] = res_ue.policy
                    v_new[d, :, zi] = res_ue.value

            # Update inclusive value and probabilities
            v_inc_new = np.zeros((n_m, n_z), dtype=np.float64)
            probs_new = np.zeros((n_d, n_m, n_z), dtype=np.float64)
            for zi in range(n_z):
                v_inc_new[:, zi], probs_new[:, :, zi] = _logsumexp_probs_2d_kernel(
                    v_new[:, :, zi], sigma_eps
                )

            # Check convergence (policy sup-norm, standard in EGM algorithms)
            sup_norm = float(np.max(np.abs(c_new - c_curr)))
            c_curr = c_new
            v_curr = v_new
            v_inc_curr = v_inc_new
            probs_curr = probs_new

            if not is_finite and sup_norm < tol:
                converged = True
                break
        else:
            if is_finite:
                converged = True
            else:
                converged = sup_norm < tol

        elapsed = time.perf_counter() - t0

        # Package solution dictionaries using ChoiceMapping for dict and array duality
        choice_policies_dict: Dict[int, np.ndarray] = {}
        choice_values_dict: Dict[int, np.ndarray] = {}
        choice_probabilities_dict: Dict[int, np.ndarray] = {}

        for d in range(n_d):
            if n_z == 1:
                choice_policies_dict[d] = c_curr[d, :, 0]
                choice_values_dict[d] = v_curr[d, :, 0]
                choice_probabilities_dict[d] = probs_curr[d, :, 0]
            else:
                choice_policies_dict[d] = c_curr[d]
                choice_values_dict[d] = v_curr[d]
                choice_probabilities_dict[d] = probs_curr[d]

        choice_policies = ChoiceMapping(choice_policies_dict)
        choice_values = ChoiceMapping(choice_values_dict)
        choice_probabilities = ChoiceMapping(choice_probabilities_dict)

        int_val = v_inc_curr[:, 0] if n_z == 1 else v_inc_curr

        meta = {
            "converged": converged,
            "n_iter": n_iter,
            "sup_norm": sup_norm,
            "backend": resolved_backend,
            "elapsed_time": elapsed,
            "sigma_eps": sigma_eps,
            "beta": beta,
            "r": self.r,
            "a_min": self.a_min,
            "horizon": self.horizon,
            "n_choices": n_d,
            "n_a": n_a,
            "n_m": n_m,
            "n_z": n_z,
        }

        return DCEGMSolution(
            asset_grid=m_grid,
            choice_policies=choice_policies,
            choice_values=choice_values,
            choice_probabilities=choice_probabilities,
            integrated_value=int_val,
            converged=converged,
            metadata=meta,
        )


# ---------------------------------------------------------------------------
# High-Level Functional Solver
# ---------------------------------------------------------------------------

def solve_dcegm(
    problem_or_a_grid: Union[DCEGMProblem, Sequence[float], np.ndarray],
    m_grid: Optional[Union[Sequence[float], np.ndarray]] = None,
    *args: Any,
    backend: str = "numpy",
    **kwargs: Any,
) -> DCEGMSolution:
    """Functional interface for solving discrete-continuous dynamic programs via DC-EGM.

    Accepts either a configured `DCEGMProblem` instance or raw grid/parameter arguments.

    Parameters
    ----------
    problem_or_a_grid : DCEGMProblem | Sequence[float] | np.ndarray
        Either a pre-built `DCEGMProblem` or next-period asset grid `a_grid`.
    m_grid : Sequence[float] | np.ndarray, optional
        Target evaluation grid for cash-on-hand M (if a_grid passed as first arg).
    backend : str, default "numpy"
        Compute backend: "numpy", "numba", "mlx", or "cupy".
    **kwargs : Any
        Additional keyword arguments passed to `DCEGMProblem` or `.solve()`.

    Returns
    -------
    DCEGMSolution
        Solved policy functions, conditional value functions, choice probabilities,
        integrated value, and presentation interface.
    """
    if isinstance(problem_or_a_grid, DCEGMProblem):
        return problem_or_a_grid.solve(backend=backend, **kwargs)

    # Extract problem kwargs vs solver kwargs
    problem_keys = {
        "n_choices", "u_fn", "u_prime", "u_prime_inv", "beta", "r",
        "income", "P_z", "z_grid", "sigma_eps", "a_min", "horizon",
        "discrete_transitions", "options", "metadata",
    }
    prob_kwargs = {k: v for k, v in kwargs.items() if k in problem_keys}
    solve_kwargs = {k: v for k, v in kwargs.items() if k not in problem_keys}

    problem = DCEGMProblem(
        a_grid=problem_or_a_grid,
        m_grid=m_grid,
        **prob_kwargs,
    )
    return problem.solve(backend=backend, **solve_kwargs)


__all__ = [
    "upper_envelope",
    "UpperEnvelopeResult",
    "ChoiceMapping",
    "DCEGMProblem",
    "DCEGMSolution",
    "solve_dcegm",
]
